### ISSUE TITLE
Using PIV for SSH through PKCS11 - Windows

### ISSUE THREAD

**Issue by francoricci** [Yubico/yubico-piv-tool#223] opened 2020-01-30 15:57 UTC
Is there a Windows tutorial like this?
[Using PIV for SSH through PKCS11](https://developers.yubico.com/PIV/Guides/SSH_with_PIV_and_PKCS11.html)
Windows seems does not work with putty and ssh certs (not public key, ssh certs)

**Comment by jmyreen** [comment] 2020-01-30 17:52
You will need to use the [PuTTY CAC](https://github.com/NoMoreFood/putty-cac/releases) fork of PuTTY. You have two options: either configure PuTTY CAC to use Windows' Crypto API or PKCS11. 

To use CAPI, introduce the YubiKey to PuTTY by pressing the "Set CAPI Cert..." button and select the certificate in the dialog that appears.

If you choose to use PKCS11, you will first need to install [OpenSC](https://github.com/OpenSC/OpenSC/wiki) for Windows and then press "Set PKCS Cert..." in PuTTY. Then browse to OpenSC's PKCS11 library.

The advantage of using CAPI is that you don't need to install OpenSC as an additional dependency, but the big disadvantage is that Windows apparently doesn't like self-signed certificates. This means the method in the article you linked to doesn't work, because you will need a signed certificate that Windows trusts. It might be possible to sign it yourself, by creating a signing key and installing the corresponding (self-signed) certificate (with all the options set correctly) as a trusted certificate root in Windows, but I haven't tried that.

**Comment by francoricci** [comment] 2020-01-30 18:05
Under OSX I have:

> ssh -I /PATH/TO/libykcs11.dylib -i rsa-cert.pub  pippo@host

File passed in -i option is the certificate in OpenSSH format signed by OpenSSH CA. This certificate is NOT inside Yubicokey.
Inside YubicoKey there are private key and public key which is wrapped in a X509 certificate non signed by Openssh CA.
(check tutorial https://developers.yubico.com/PIV/Guides/SSH_with_PIV_and_PKCS11.html )

When I use Putty CAC, and I select "Set CAPI Cert..." button I retrive certificate in YubicoKey.
Windows successfully connect to Yubicokey buI think Putty CAC support only ssh public key authentication and not SSH certs authentication.
The problem is that Windows not have a native SSH client that I can use like OSX and Unix

**Comment by francoricci** [comment] 2020-01-30 18:23
I think that this putty CAC issue could help to understand my problem:
[[FR] openssh-certificates #38](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=2ahUKEwibsuXC96vnAhUpwAIHHW4pCHQQFjAAegQIBBAB&url=https%3A%2F%2Fgithub.com%2FNoMoreFood%2Fputty-cac%2Fissues%2F38&usg=AOvVaw3utpVF7wgZku-ylCDFPER-)

**Comment by jmyreen** [comment] 2020-01-30 19:38
Well, as I said I have not used a YubiKey with PuTTY CAC using CAPI, because Windows didn't like the certificate on the YubiKey (though Windows in typical manner didn't say _why_ it didn't like it.) What I _have_ managed to do is use PuTTY CAC with my YubiKey and PKCS#11 using OpenSC. I have _also_ been able to use CAPI using my electronic ID card, and that card is similar to a PIV card, and certainly knows nothing about "ssh certs".

**Comment by dainnilsson** [comment] 2020-01-31 12:24
Just wanted to note here that you can use the PKCS#11 module in yubico-piv-tool 2.0.0 with PuTTY CAC (ykcs11) instead of OpenSC if you prefer. I just tested it to confirm that it works.

**Comment by jmyreen** [comment] 2020-02-03 18:13
I can confirm my hypothesis that a self-signed certificate is no good for Windows. This is a Windows CAPI problem (or feature, depending on whom you ask), not a Yubikey or PuTTY CAC problem.

Here's what I did to make PuTTY CAC work with CAPI: I got a free S/MIME Email Certificate from [actalis.it](https://www.actalis.it/products/certificates-for-secure-electronic-mail.aspx) and installed it on my Yubikey 5. Windows accepts the certificate because it is properly signed (not self-signed) and the certificate path up to Actalis's root certificate are known to Windows.

A word of warning, though, if you go this route: you can not provide your own private key, but the private key corresponding to the public key in the certificate is generated by Actalis. This means you will have to trust Actalis not to misuse the private key.

I can also confirm that @dainnilsson 's suggestion to use the ykcs11 module works fine.

**Comment by francoricci** [comment] 2020-02-04 09:16
Probably you are about public key authentication method and not OpenSSH certs authentication: it's different.
Putty doesn't support SSH certs, it's only support public key authentication, retrieving secret key in PIV devices as yubico key.

I found the solution installing OpenSSH Windows port: [ PowerShell /Win32-OpenSSH ](https://github.com/PowerShell/Win32-OpenSSH/releases/tag/v8.1.0.0p1-Beta)
PKCS support was introduced in version 8.0.0.0 (Jun 24, 2019)!! 

Once installed, by a windows cmd prompt:
`ssh.exe -I yubico-piv-tool/bin/libykcs11-1.dll -i cert.pub user@host`
File passed in -i option is the certificate in OpenSSH format signed by OpenSSH CA!!
All works well!!!

It was great if it's possible to insert this tutorial in yubico developer pages: [https://developers.yubico.com/PIV/Guides/SSH_with_PIV_and_PKCS11.html ](https://developers.yubico.com/PIV/Guides/SSH_with_PIV_and_PKCS11.html )

**Comment by jmyreen** [comment] 2020-02-04 10:04
@francoricci I don't know if PuTTY supports "SSH Certs". But when configured to use a certificate for authentication (by clicking the "Set PKCS Cert..." or "Set CAPI Cert..." in the settings) it uses **X.509** certificates, as retrieved from the YubiKey. My experiments confirm that both the PKCS API and Microsoft's CAPI work on PuTTY CAC using these certificates, but CAPI is a bit more picky about which certificates it accepts.

The private key is never retrieved from the Yubikey; it is operated upon inside the Yubikey.

"SSH Certs" are a newer invention than X.509 certificates. X.509 certificates were "not invented here", so OpenSSH had to come up with their own format...

Great to see that OpenSSH now also supports PKCS on Windows.

**Comment by jmyreen** [comment] 2020-02-04 17:21
Actually, the new version of Windows OpenSSH also works with PKCS#11 and a X.509 certificate stored on the YubiKey, just as described on the [guide page](https://developers.yubico.com/PIV/Guides/SSH_with_PIV_and_PKCS11.html). For example:

`ssh.exe -I ...\yubico-piv-tool-2.0.0-win64\bin\libykcs11-1.dll user@host`

So there is really no need to change the page for Windows, other than perhaps mentioning that the OpenSSH client version should be at least 8.0.0, and that libykcs11-1.dll can be used as the PKCS#11 library.

**Comment by francoricci** [comment] 2020-02-06 14:06
**SSH certs are different from SSH public key authentication.**
Public key authentication needs for a private key and a public key; private key will be passed by PKCS11 provider (SSH public key starts with **ssh-dss** ...)
SSH certs authentication needs for a private key and SSH public certs (not X509). Private key will be passed by PKCS11 provider while SSH public cert will be passed by line command: it can't be inside yubico key because it doesn't support SSH certs.
(SSH certs starts with **ssh-rsa-cert-v01@openssh.com** ...)

For SSH public key authentication I make:
`ssh.exe -I ...\yubico-piv-tool-2.0.0-win64\bin\libykcs11-1.dll user@host`

for SSH certs authentication I make:
`ssh.exe -I yubico-piv-tool/bin/libykcs11-1.dll -i cert.pub user@host`

As you can see in the last command I use "-i" option to pass SSH public certs.
Is Putty able to sue a PKCS11 provider and a SSH public cert?

Anyway, with my last [post](https://github.com/Yubico/yubico-piv-tool/issues/223#issuecomment-581813206) I solved.

Thanks!

**Comment by qpernil** [comment] 2020-02-07 11:57
ykcs11 from yubico-piv-tool 2.0.0 has been tested to work with OpenSSH 8.x using both RSA and EC keys. I see no reason it wouldn't work on Windows as well.

It is worth noting that ykcs11 provides access to attestations, which are simply X.509 certificates signed by an attestation key in the YubiKey. The signing certificate can be retrieved from slot 0xf9 (CKA_ID 0x19). Attestations are session objects, so won't be found if an application only looks for CKA_TOKEN objects.
(They are session objects because they do not persist, and will be different each time they are generated. They will of course contain the same public key each time, the one for the private key with the same CKA_ID)

I will close this issue now as I think it is resolved with the 2.0.0 release. Please reopen if I'm mistaken.

**Closed by qpernil** 2020-02-07 11:57 UTC
