### ISSUE TITLE
PIV Keys loaded / used in the Wrong Order on Windows 10

### ISSUE THREAD

**Issue by FlyingSheepOnSailfish** [Yubico/yubico-piv-tool#421] opened 2023-01-16 10:53 UTC
On Windows 10 the OpenSSH ssh-agent is loading and using the PIV keys from my Yubico 5c Nano in the wrong order.
It is loading the Attestation key first, and the Authentication key second.

On my Mac the Authentication key is loaded / used first.

Windows 10
```
ssh-add -L
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCvgZW...ZLWFcNCf/hZ C:/Program Files/Yubico/Yubico PIV Tool/bin/libykcs11.dll
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDEFM8...xNE/rLEc2VJ C:/Program Files/Yubico/Yubico PIV Tool/bin/libykcs11.dll
```
macOS
```
ssh-add -L
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDEFM8...xNE/rLEc2VJ Public key for PIV Authentication
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCvgZW...ZLWFcNCf/hZ Public key for PIV Attestation
```

This means that
1) Git commands from the Windows command line will give the error below because it first tries to authenticate with the attestation key, but will then try the second key and succeed (it tries both keys if the first fails).

`sign_and_send_pubkey: signing failed for RSA "Public key for PIV Attestation" from agent: agent refused operation`

2) Git operations from Windows Eclipse/JGIT fail. Presumably JGIT aborts on the error above, and does not try the second key.

Setting LogLevel to DEBUG1 gives:
```
debug1: Will attempt key: Public key for PIV Attestation RSA SHA256:BmZFU+D2c8opTkyt4zO0JHpUNr5Oh8u3AfbkkhRpOrk token agent
debug1: Will attempt key: Public key for PIV Authentication RSA SHA256:n9Uotcz9uQVJKpSj3h0GnTuVT1fd8g7CCTUWn+1McMA token agent
...
debug1: SSH2_MSG_EXT_INFO received
debug1: kex_input_ext_info: server-sig-algs=<ssh-ed25519-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp256-cert-v01@openssh.com,sk-ssh-ed25519-cert-v01@openssh.com,sk-ecdsa-sha2-nistp256-cert-v01@openssh.com,rsa-sha2-512-cert-v01@openssh.com,rsa-sha2-256-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ssh-dss-cert-v01@openssh.com,sk-ssh-ed25519@openssh.com,sk-ecdsa-sha2-nistp256@openssh.com,ssh-ed25519,ecdsa-sha2-nistp521,ecdsa-sha2-nistp384,ecdsa-sha2-nistp256,rsa-sha2-512,rsa-sha2-256,ssh-rsa,ssh-dss>
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey
debug1: Next authentication method: publickey
debug1: Offering public key: Public key for PIV Attestation RSA SHA256:BmZFU+D2c8opTkyt4zO0JHpUNr5Oh8u3AfbkkhRpOrk token agent
debug1: Server accepts key: Public key for PIV Attestation RSA SHA256:BmZFU+D2c8opTkyt4zO0JHpUNr5Oh8u3AfbkkhRpOrk token agent
sign_and_send_pubkey: signing failed for RSA "Public key for PIV Attestation" from agent: agent refused operation
debug1: pkcs11_k11_free: parent 000002462369AF80 ptr 0000000000000000 idx 0
debug1: Offering public key: Public key for PIV Authentication RSA SHA256:n9Uotcz9uQVJKpSj3h0GnTuVT1fd8g7CCTUWn+1McMA token agent
debug1: Server accepts key: Public key for PIV Authentication RSA SHA256:n9Uotcz9uQVJKpSj3h0GnTuVT1fd8g7CCTUWn+1McMA token agent
debug1: pkcs11_k11_free: parent 000002462369B020 ptr 0000000000000000 idx 0
debug1: pkcs11_k11_free: parent 000002462369B520 ptr 00000246236A34D0 idx 0
debug1: pkcs11_provider_unref: provider "C:\\Program Files\\Yubico\\Yubico PIV Tool\\bin\\libykcs11.dll" refcount 3
debug1: pkcs11_k11_free: parent 000002462369B8E0 ptr 00000246236A37D0 idx 0
debug1: pkcs11_provider_unref: provider "C:\\Program Files\\Yubico\\Yubico PIV Tool\\bin\\libykcs11.dll" refcount 2
Authenticated to github.acme.com ([169.60.70.162]:22) using "publickey"
```

I am using:
yubico-piv-tool 2.2.0
https://github.com/PowerShell/Win32-OpenSSH/releases/download/v9.1.0.0p1-Beta/OpenSSH-Win64-v9.1.0.0.msi

I am not sure if the error is on the Yubico or OpenSSH code.

Note I first tried using the version of OpenSSH from Microsoft, but could not get to work at all.

**Comment by qpernil** [comment] 2023-01-27 14:32
To me this looks like an SSH configuration issue, on the server side, as it seems to accept the attestation key. This would indicate to me that is has been configured on the server in the authorized_keys file. Can you check if that is the case ?

**Comment by FlyingSheepOnSailfish** [comment] 2023-02-26 21:46
Hi Per
Thank you for your answer, and sorry it took me so long to get back to you. To be honest I had given up hope of an answer, and was no longer tracking this issue.

The server is GitHub Enterprise, so sadly out of my control.

However in playing around, and trying to find a creative / pragmatic workaround, one idea that occurred to me, was to submit both keys to GitHub. However GitHub refused to accept the Attestation key. The error was something like "already used", so presumably GitHub was already loaded with that key, just not against my account.

I originally ordered the Nano 5c for my Mac, and only later tried it on my Lenovo P50. As the only USB-C port on the P50 is hidden at the back, I have subsequently purchased a Yubico YubiKey 5 Nano that fits on the old-school USB ports on the side of the P50. Surprisingly the new YubiKey seems to load the Public Keys in the correct expected order on Windows on the P50 (unlike the Nano 5c). Due to other issues I have not had the time to experiment and find out what is different between the tow YubiKeys. e.g firmware version etc.

Looking more closely at the debug output, while the Server initially accepts the Attestation key, it also outputs 'signing failed for RSA "Public key for PIV Attestation" from agent:' Authentication is only successful when the client subsequently sends the Authentication key.

And surely the priority in which the client presents the keys has nothing to do with the server?

Cheers

Chris

**Comment by qpernil** [comment] 2023-02-27 13:18
The attestation key is shared between a number of YubiKeys for privacy reasons, so as to not identify the particular YubiKey. As such it is also a special key that cannot be used for any other purpose. Hence the failure if the server accepts it. If this happens. I can't really help with the github configuration. But an attestation key shouldn't be registered for sure.

**Comment by qpernil** [comment] 2023-02-27 13:24
I think there is a way to specify what key(s) to use, maybe in a ssh config file.

**Comment by qpernil** [comment] 2023-02-27 15:25
As I understand in in this case the problem is that somebody else has registered the attestation key, and you can't do anything about it. If that is correct than I recommend looking at configuring your ssh client to only offer specific keys.

**Comment by qpernil** [comment] 2023-03-01 13:21
About the order of keys - libykcs11 presents keys in CKA_ID order, so the attestation key comes after any usable keys. The fact that it chooses it first is out of control of our libraries, as far as I can tell.

**Comment by FlyingSheepOnSailfish** [comment] 2023-03-01 22:52
Hi Per
Thanks for your feedback. I hope I can find time tomorrow to experiment with both my YubiKeys again on Windows. It is interesting that I seem to have the key order problem with the 5c Nano YubiKey, but not with the new 5 Nano.

As you guess, it is quite possible that some kind soul registered the attestation key as well as the authentication key, presumably because he / she had also found that the attestation key was presented first - I confess that I tried that as a workaround, but my attempt was refused.

It is equally unclear to me what exactly dictates the order in which ssh uses the keys: if it is down to ssh, or down to your libraries...  and on Windows there are multiple possible and conflicting ssh-agent implementations available

**Comment by FlyingSheepOnSailfish** [comment] 2023-03-02 14:04
As promised I was able to do some more experimentation with both the YubiKeys on Windows 10.

**YubiKey 5 C Nano key Firmware=5.2.7**
```
debug3: ssh_get_authentication_socket_path: path '\\\\.\\pipe\\openssh-ssh-agent'
debug2: get_agent_identities: ssh_agent_bind_hostkey: invalid format
debug1: get_agent_identities: agent returned 2 keys
debug1: pkcs11_k11_free: parent 000001D41560B610 ptr 0000000000000000 idx 0
debug1: pkcs11_k11_free: parent 000001D41560B750 ptr 0000000000000000 idx 0
debug1: Will attempt key: Public key for PIV Attestation RSA SHA256:BmZFU+D2c8opTkyt4zO0JHpUNr5Oh8u3AfbkkhRpOrk token agent
debug1: Will attempt key: Public key for PIV Authentication RSA SHA256:n9Uotcz9uQVJKpSj3h0GnTuVT1fd8g7CCTUWn+1McMA token agent
```


**YubiKey 5 Nano Firmware=5.4.3**
```
debug3: ssh_get_authentication_socket_path: path '\\\\.\\pipe\\openssh-ssh-agent'
debug2: get_agent_identities: ssh_agent_bind_hostkey: invalid format
debug1: get_agent_identities: agent returned 2 keys
debug1: Will attempt key: C:/Program Files/Yubico/Yubico PIV Tool/bin/libykcs11.dll RSA SHA256:BmZFU+D2c8opTkyt4zO0JHpUNr5Oh8u3AfbkkhRpOrk agent
debug1: Will attempt key: C:/Program Files/Yubico/Yubico PIV Tool/bin/libykcs11.dll RSA SHA256:n9Uotcz9uQVJKpSj3h0GnTuVT1fd8g7CCTUWn+1McMA agent
debug1: Will attempt key: Public key for PIV Authentication RSA SHA256:8j8Emi1UAWJ/oZyYZi6gqW3exfTarbbuQ2hQ3yEFh7I token
debug1: Will attempt key: Public key for PIV Attestation RSA SHA256:54W0/9rkv84M3pwsFa7qvWkCeQGbkWlwSkvk1fcsrV0 token
```

So, on the same Windows 10 laptop, with the same OpenSSH Agent running, the "old" 5C Nano consistently tries the Attestation key first (NOT OK), while the newer Nano Key tires the Authentication key first (OK). I suspect this maybe down to the firmware version.

I also tried your suggestion of  ssh -i "pkcs11:id=%01" example.com. but that gave me:
`Warning: Identity file pkcs11:id=%01 not accessible: No such file or directory.`

**Comment by qpernil** [comment] 2023-03-03 08:37
Looks like your YubiKeys have different attestation keys, and I'd guess only one is registered on the server side

**Comment by qpernil** [comment] 2024-05-21 14:24
Closing this issue now as it seems to be a configuration issues outside the control of yubico-piv-tool

**Closed by qpernil** 2024-05-21 14:24 UTC
