### ISSUE TITLE
PIN must be UTF-8.

### ISSUE THREAD

**Issue by dwmw2** [Yubico/yubico-piv-tool#96] opened 2016-10-03 15:36 UTC
The PKCS#11 specification mandates that the PIN is in UTF-8. We should check this, and YKCS11 should return `CKR_ARGUMENTS_BAD` whenever invalid UTF-8 byte sequences are seen in `C_Login()`, `C_SetPIN` or `C_InitPIN()` calls.

If we're running in a legacy 8-bit locale, then where we accept a PIN on a command line or from stdin, that needs to be converted _to_ UTF-8 by iconv, before it's set on the token.

**Comment by a-dma** [comment] 2016-10-04 07:34
I'm not sure about this. The problem is that PIV only accepts ASCII, numeric PINs

**Comment by dwmw2** [comment] 2016-10-04 08:20
Heh, you got that edit in while I was disproving it...

```
$ yubico-piv-tool -a change-pin -N fish♥  -P 1234
Successfully changed the pin code.
$ curl -E 'pkcs11:manufacturer=piv_II;id=%01;pin-value=fish♥' -k https://localhost:4443
… works …
```

**Comment by dwmw2** [comment] 2016-10-04 22:19
Just for clarity: You don't have to accept *all* characters. But the input character set encoding MUST be UTF-8, not just passed through in legacy 8-bit charsets.

Whatever locale you run in, if the password is 'naïve', that means the bytes you give to the hardware are (UTF-8) `6e 61 c3 af 76 65`. And those are the bytes which an application must give to the PKCS#11 functions.

So I don't care if yubico-piv-tool is running in a legacy ISO8859-1 locale, where that password comes in as the bytes `6e 61 ef 76 65`. Or if it's running on the Windows console with CP-437, where the input bytes are `6e 61 8b 76 65`. Or if it's in the Macintosh character set where it's `6e 61 95 76 65`. Those are all different ways of representing the same password; none of which should ever be seen by the token or the PKCS#11 provider.

If the password is `naïve`, then the bytes you feed to the token are `6e 61 c3 af 76 65`. And those are the bytes which the PKCS#11 functions expect to receive from an application.

**Comment by qpernil** [comment] 2020-02-10 15:28
Since PIV specifies that the PIN must be numeric the above would be an invalid PIN code. Yubico PIV does not enforce that. No plans to change this behavior for now, as doing so would be a platform-specific mess. Closing the issue.

**Closed by qpernil** 2020-02-10 15:28 UTC
