### ISSUE TITLE
ykcs11: 'agent refused operation'  OS X 10.13.6

### ISSUE THREAD

**Issue by udf2457** [Yubico/yubico-piv-tool#158] opened 2018-08-12 16:15 UTC
Hi,

I am aware of #88 featuring @paul-pearce & co, but that does not help and is also partly obsolete because PIV functionality is now built-in to OS X.  I have also seen  #118, but not much of interest there, partly for the same reasons.

To summarise where I am at:

Basic setup has been done:
```
yubico-piv-tool -achange-pin
yubico-piv-tool -achange-puk
yubico-piv-tool -k -agenerate -s9c -AECCP384
```

This:
`ssh-add -s/Users/foobar/Work/yubico-piv-tool-1.6.0-mac/lib/libykpiv.dylib`

Does not work, it yields `agent refused operation`.

So then I compiled the latest versions of `libressl` (2.8.0) and `openssh` (7.7p1) from scratch, thinking it might be something with the Apple binaries (OS X 10.13.6 ships with OpenSSH_7.6p1 compiled against LibreSSL 2.6.2), but that yields the same `agent refused operation`, e.g.:

`libre/bin/ssh-add -s/Users/foobar/Work/yubico-piv-tool-1.6.0-mac/lib/libykcs11.dylib`

I then read about the whitelist, and so I tried this:

```
libre/bin/ssh-agent -P/Users/foobar/Work/yubico-piv-tool-1.6.0-mac/lib/*

SSH_AUTH_SOCK=/path/to/sock/agent.96574 libre/bin/ssh-add -s/Users/foobar/Work/yubico-piv-tool-1.6.0-mac/lib/libykcs11.dylib
```

That yields the same errorL

> Could not add card "/Users/foobar/Work/yubico-piv-tool-1.6.0-mac/lib/libykcs11.dylib": agent refused operation

And running `ssh-agent` in debug (-d) mode doesn't yield much of interest:

```
debug2: fd 3 setting O_NONBLOCK
debug3: fd 4 is O_NONBLOCK
debug1: process_message: socket 1 (fd=4) type 20
debug1: process_add_smartcard_key: add /Users/foobar/Work/yubico-piv-tool-1.6.0-mac/lib/libykcs11.dylib
```

Finally, I should add that for all the tests above, I have also tried the `/usr/local/lib` trick as mentioned i the previous issues, and that made no difference.

**Comment by udf2457** [comment] 2018-08-12 21:28
For the benefit of anyone who finds this through their favorite search engine, I think I should publish a solution to the problem to save you many hours of wasted time.

The underlying cause is this:  https://bugzilla.mindrot.org/show_bug.cgi?id=2474

Which effectively tells you that despite a bug report opened in 2015 and many patches provided by the community, **_OpenSSH has no ECC support for PKCS11, only RSA._**

The error messages generated and shown in my original question are therefore incorrect and pointless.

I deleted the original key on my Yubikey which used ECCP384 and generated an RSA2048 key.  It worked fine after that.

So, I have two recommendations:

1. The people at Yubikey update all possible documentation (PDFs, websites) to point this out !
2. Any interested parties put pressure on OpenSSH to incorporate one of the many patches provided by the community to OpenSSH.

**Comment by paul-pearce** [comment] 2018-08-20 21:08
Additional bit of information:

Last time I looked ssh-agent whitelisting was non-functional, despite it being documented in the man pages. The only solution was to move the library into one of the predefined "safe" library paths.

**Comment by simongillet** [comment] 2018-10-27 09:47
This works:
alias ssh-agent='export OPENSC_LIBS=$(brew --prefix opensc)/lib;export SSH_AUTH_SOCK="";eval `/usr/local/bin/ssh-agent -s  -P /usr/local/lib/*,/usr/local/Cellar/opensc/*/lib/*.so,/usr/local/opt/opensc/lib/*.so,/usr/local/Cellar/yubico-piv-tool/*/lib/*.dylib`'
alias yubinit='export SSH_AUTH_SOCK="";eval `/usr/local/bin/ssh-agent -s  -P /usr/local/lib/*,/usr/local/Cellar/yubico-piv-tool/*/lib/*.dylib`;ssh-add -s /usr/local/lib/libykcs11.dylib'

More info there:
https://gist.github.com/simongillet/230e0329f6630919a20a84ed618928f3

**Comment by simongillet** [comment] 2018-10-27 17:03
You get also get it to work with the MacOS provided SSH:
https://gist.github.com/simongillet/cf92d1ce5708a0a153b4157d6813053b

**Comment by micolous** [comment] 2019-03-05 11:55
It looks like we're conflating a few different issues here -- the title is somewhat misleading as this specifically relates to the use of ECCP384 keys, not getting ykcs11 working on OSX.

#118 seems to be the canonical bug for the sorry state of PKCS11 authentication on OSX.

**Comment by qpernil** [comment] 2020-02-07 15:21
yubico-piv-tool 2.0.0 is out and contains major upgrade to ykcs11. It has been tested to work with EC keys with OpenSSH 8.x. Please try that version.

I'm closing this issue, please re-open if the problem persists.

**Closed by qpernil** 2020-02-07 15:21 UTC

**Comment by brechtm** [comment] 2022-08-11 15:37
I would like to report that getting PIV-based SSH authentication working on macOS Monterey has been an absolutely **horrendous** experience. It took me hours and hours to figure everything out. Here are some of the issues I encounters (as far as I can remember them):
- Following the instructions in [Using PIV for SSH through PKCS #11](https://developers.yubico.com/PIV/Guides/SSH_with_PIV_and_PKCS11.html), one of the first steps failed. After googling the error, I read that yubico-piv-tool is on the way out to be replaced by ykman, which was able to generate keys and certificates.
- Since the official documentation was outdated, I somehow ended up following guides that suggested installing the OpenSC cask through Homebrew. I was able to successfully log into an SSH server with an ECCP256 key on my Yubikey 5 NFC.
- After looking for the cause for hours, I finally discovered that [OpenSC broke PIV authentication for logging into macOS](OpenSC/OpenSC#2590)! So I uninstalled OpenSC, but I'm left to configure PIV SSH Authentication in another way.
- Again, after a long search, I found that Apple ships a PKCS11 provides with the OS: [ssh-keychain.dylib](https://playbooks.idmanagement.gov/piv/engineer/ssh/#ssh-from-macos). But that doesn't work with the Yubikey however, for whatever reason. No mention of it in Yubico's docs.
- Other articles and bugtracker threads point me to _libykcs11.so_. But it appears this ships with yubico-piv-tool, so I'm not very confident this will work (since I read earlier it was deprecated in favor of ykman).
- Unfortunately, ssh-agent shipped with macOS will refuse to load _libykcs11.dylib_ from the location where Homebrew installs it. Because it can't simply say that in plain language, I was in for several more hours of hunting for the reason why this wasn't working. More information: [SSH PIV authentication on MacOS without errors](https://somm15.github.io/yubikey/macos/ssh/2018/11/20/welcome-to-jekyll.html)
- Additionally, the combination of Monterey's OpenSSH and _libykcs11.so_ do not support EC keys. This is not mentioned in the Yubico docs either. `ssh-keygen -D /usr/local/lib/libykcs11.dylib` does list an RSA key, but that turned out to be the key in slot f9, which is not useable for SSH authentication (why does ssh-keygen list it then?).

After all this, I can't say that I am a satisfied customer. I am aware that Apple likes to move stuff around with every OS upgrade, which is part of the problem here. But Yubico can make the experience infinitely more smooth for their customers by making sure their documentation is up to date. Please!

I chose to generate an RSA key in slot 9c instead of overwriting my ECCP256 key in slot 9a:
```
ykman piv keys generate --pin-policy NEVER --touch-policy ALWAYS 9c 9c.pem
ykman piv certificates generate -s "SSH Key" -d 10950 9c 9c.pem
```

After telling ssh-keygen to accept _/usr/local/lib/libykcs11.dylib_ run with the `-P` argument (see [this gist](https://gist.github.com/vancluever/de1c3985c8f9e2a3c4bdc42a057e075e) and [that gist](https://gist.github.com/somm15/cf92d1ce5708a0a153b4157d6813053b)), these work:
```
ssh-keygen -D /usr/local/lib/libykcs11.dylib
ssh-add -s /usr/local/lib/libykcs11.dylib
```

I need to add _libykcs11.so_ to the agent because I wanted to avoid having to enter the PIN every time I connect (ykman's `--pin-policy` doesn't seem to have any effect).

But then there's the issue that you need to remove and add _libykcs11.so_ from/to the agent if the Yubikey was unplugged ([#88#issuecomment-279102884](https://github.com/Yubico/yubico-piv-tool/issues/88#issuecomment-279102884)). The script below, which I named `yubissh` helps with that (not tested thoroughly!).

**Note:** you need to create the `~/.local/share/yubissh` directory first.

```bash
#!/bin/bash

# Wrapper for 'ssh' that only asks for your Yubikey's PIN when needed
#
# Adds the PKCS11 provider to the SSH agent if needed, but only if the Yubikey
# is plugged in. Also handles the fact that the PKCS11 provider needs to be
# removed and added again if the Yubikey was unplugged in the meantime.
# (https://github.com/Yubico/yubico-piv-tool/issues/88#issuecomment-279102884)

SESSION_ID_FILE=$HOME/.local/share/yubissh/last_session_id

# https://gist.github.com/vancluever/de1c3985c8f9e2a3c4bdc42a057e075e
if [ -n "${SSH_AUTH_SOCK_LOCAL}" ]; then
  export SSH_AUTH_SOCK="${SSH_AUTH_SOCK_LOCAL}"
fi

if [[ $(sc_auth identities) ]]; then
    PREV_SESSION_ID=$(cat $SESSION_ID_FILE 2>/dev/null)
    SESSION_ID=$(ioreg -r -p IOUSB -n "YubiKey OTP+FIDO+CCID" -a | plutil -extract "0.sessionID" raw -)
    if [[ "$SESSION_ID" != "$PREV_SESSION_ID" ]]; then
        ssh-add -e /usr/local/lib/libykcs11.dylib
        ssh-add -s /usr/local/lib/libykcs11.dylib
    fi
    echo $SESSION_ID > $SESSION_ID_FILE
fi

ssh "$@"
```

**Comment by udf2457** [comment] 2022-08-11 16:15
@ brechtm  I agree that the Yubikey docs are shockingly bad.

And if you think basic PIV stuff is hard to get going, wait until the day when you have the pleasure of spending 600/900 on a so-called YubiHSM.  Only to find the documentation severely lacking and the support response non-existent.

I swore I'd never use a YubiHSM again after that.   I still use the basic YubiKey because there's nothing really comparable in terms of form factor and functionality.  But whichever way, I do wish Yubi would get off their backside and update their docs (and remove all the obsolete docs from the website whilst they're at it.. because that just sends people on a wild goose chase).

Meanwhile, back to your Mac comment.  My experience was much easier than yours, I'll see if I can dig up my notes.

**Comment by udf2457** [comment] 2022-08-11 16:21
@brechtm Just found my notes, they're a bit terse, but basically as you discovered once you have `libykcs11.dylib` in place in `/usr/local/lib/`, everything else falls into place pretty easily with the use of a command flag or two, and then adding `PKCS11Provider /usr/local/lib/libykcs11.dylib` to `~/.ssh/config`

 I can't remember where but `libykcs11.dylib` is available via a zip file or something on the Yubi website.

**Comment by mouse07410** [comment] 2022-08-11 20:48
I agree that YubiHSM documentation is rather poor. 

On the other hand, I've been using YubiHSM with MacOS quite successfully for a few years, mostly in experimental projects (reasons - inertia of our IT, and regulatory concerns, which push the organization towards solution that allows to avoid the blame in case...). 

I'm eagerly waiting to see support of NIST PQC algorithms by YubiHSM.

**Comment by a-dma** [comment] 2022-08-12 07:46
Thanks @brechtm and others. Needless to say this kind of feedback is significantly more useful. There is a longer conversation to be had about documentation and constantly having to play catch-up with a lot of other moving parts like OS upgrades and third-party project changes, but this is not the place for it.

Ultimately the goal is to make the user experience as good as it can be. I hear you (all) when you say that we're not there, but there's a lot of things at play. I'll pass the feedback along and take the conversation internally.

Finally, regarding YubiHSM, that has a different set of challenges, but please open issues in the relevant projects or a support ticket if nothing applies. Feature requests for hardware devices are a separate topic, but bug reports, contributions and documentation change requests and suggestions are always welcome.

**Comment by aveenismail** [comment] 2022-08-12 09:06
@brechtm In addition to what @a-dma wrote, I just want to mention for the sake of clarity that it's YubiKey PIV Manager that has been deprecated. yubico-piv-tool (including the ykcs11 module) is still maintained and fully supported with no plans to retire it as of yet.

**Comment by brechtm** [comment] 2022-08-12 09:41
> @brechtm In addition to what @a-dma wrote, I just want to mention for the sake of clarity that it's YubiKey PIV Manager that has been deprecated. yubico-piv-tool (including the ykcs11 module) is still maintained and fully supported with no plans to retire it as of yet.

Yes, I see now that I misunderstood the comment I linked to. But there seems to be quite some overlap between yubico-piv-tool and ykman, which is confusing. Are you planning on supporting these both or will ykman replace the former eventually?

**Comment by aveenismail** [comment] 2022-08-12 10:19
Both will be supported. Even though there's overlap when it comes to the YubiKey's PIV application, the two products have different use cases. The ykman is a tool to manage the YubiKey with its different applications (PIV, FIDO, OTP..etc). yubico-piv-tool is mainly a C library and a PKCS11 module that manages only the PIV application. While yubico-piv-tool as a command line tool can fully be used to manage the YubiKey PIV application just as well as ykman, there are few edge cases where the functionality is available through yubico-piv-tool but not ykman. See https://developers.yubico.com/PIV/Tools.html for some more details
