### ISSUE TITLE
Pin-policy seems to be ignored for ssh keys

### ISSUE THREAD

**Issue by lava** [Yubico/yubico-piv-tool#303] opened 2021-05-12 22:44 UTC
Roughly following the instructions [here](https://developers.yubico.com/PIV/Guides/SSH_user_certificates.html) I generate my key using `--pin-policy=never`:

```
yubico-piv-tool -a generate -s 9e -A RSA2048 --pin-policy=never --touch-policy=always -o public.pem
```

I also store it in slot 9e, which apparently has no pin policy by default.

And yet, when I try to use the key, I get asked for a PIN:
```
$ ssh -I /usr/lib/x86_64-linux-gnu/libykcs11.so private@localhost
Enter PIN for 'YubiKey PIV #15426330': 
```

Is there any way to use SSH login with only touch and no PIN requirement?

**Comment by josesolis2201** [comment] 2021-09-06 21:09
I am having this exact issue. I don't know if I misunderstood the documentation or what but the ykcs11.so seems to be ignoring the pin-policy=never and pin-policy=once. It correctly evaluates the touch policy but ignores the pin policy.

**Comment by qpernil** [comment] 2022-02-02 20:17
I apologize, I was wrong in saying all others have pin policy 'once'. Slot 9c has 'always' by default, slot 9e has 'never' by default, and the others have 'once' by default. Im talking about PIN policy that actually gets set on new keys in PIV when generated or imported. Touch policy is always 'never' by default. libykcs11 currently only supports the CKA_ALWAYS_AUTHENTICATE attribute in relation to this, driven by a static table that returns TRUE for slot 9c and false for all others.

**Comment by ceseale** [comment] 2022-02-06 03:42
@qpernil when would the next version get released with #345?

**Comment by qpernil** [comment] 2022-05-11 11:56
This feature is present in release 2.3.0. Closing this issue now, please open a new one if there are still problems.

**Closed by qpernil** 2022-05-11 11:56 UTC

**Comment by Manouchehri** [comment] 2022-11-01 04:28
> I am having this exact issue. I don't know if I misunderstood the documentation or what but the ykcs11.so seems to be ignoring the pin-policy=never and pin-policy=once. It correctly evaluates the touch policy but ignores the pin policy.

@josesolisrosales / @qpernil: Even in 2.3.0, my `ykman piv keys generate -a RSA2048 --pin-policy never --touch-policy never 9e pubkey.pem && ykman piv certificates generate --subject "demo" -d 3650 9e pubkey.pem` seems to still require a PIN when using `systemd-cryptenroll`.

Am I missing something?

**Comment by Manouchehri** [comment] 2022-11-01 04:54
See https://github.com/systemd/systemd/issues/23479#issuecomment-1297982175 for more context on what I'm doing. =)

**Comment by qpernil** [comment] 2022-11-01 09:23
I'm not versed enough in systemd to tell what pkcs11 module it would be using in this case. And just to clarify, ykman is not part of yubico-piv-tool. So to me it looks like libykcs11 is possibly only used when listing the keys.

But all of the above is likely moot anyway, as there isn't any way a pkcs11 module can tell an application that no pin is needed _per key_. The only way would be to not set CKF_LOGIN_REQUIRED, to which an application should conclude that no key on the module requires PIN at all. Per key we only have CKA_ALWAYS_AUTHENTICATE, which can only say 'once' or 'always'. libykcs11 does set CKF_LOGIN_REQUIRED as it is better for an application to ask for PIN too often than too seldom. The cosequences of the first are just a PIN code entered unnecessarily, the latter would case many operations to fail (for keys that do require PIN).

**Comment by qpernil** [comment] 2022-11-01 09:34
And a final comment - The YubiKey supports PIN policy being explicitly set. This is a proprietary extension that is not part of the PIV specification. As such other pkcs11 module than libykcs11 might only base the CKA_ALWAYS_AUTHENTICATE flag on hard-coded values based on the PIV spec, which specifies how these should be set per key. The YubiKey matches the spec unless policies are overridden when keys are created. So for this flag it might matter if libykcs11 is used or not.

**Comment by mouse07410** [comment] 2022-11-01 11:06
Would it not make more sense to use 9a slot for what you're doing? By insisting on 9e I think you're looking for trouble.

**Comment by Manouchehri** [comment] 2022-11-01 14:30
> Would it not make more sense to use 9a slot for what you're doing? By insisting on 9e I think you're looking for trouble. 

@mouse07410 Isn't 9e meant to not ask for a pin by design?

**Comment by qpernil** [comment] 2022-11-01 18:59
I’m not sure what you mean, can you elaborate? Trouble in what sense?Skickat från min iPhone1 nov. 2022 kl. 12:06 skrev Mouse ***@***.***>:﻿
Would it not make more sense to use 9a slot for what you're doing? By insisting on 9e I think you're looking for trouble.

**Comment by Manouchehri** [comment] 2022-11-06 13:45
@qpernil Even when using `-I` directly on macOS, I still get prompted for a PIN. Do you know of any standard application that this isn't a problem with..?

```sh
ykman piv reset -f
ykman piv keys generate -a RSA2048 --pin-policy never --touch-policy never -m 010203040506070801020304050607080102030405060708 83 pubkey.pem 
ykman piv certificates generate --subject "demorsa2048" -P 123456 -m 010203040506070801020304050607080102030405060708 -d 3650 83 pubkey.pem
```

```
dave@mbp /tmp % ssh -I /opt/homebrew/lib/libykcs11.dylib 192.168.22.102
Enter PIN for 'YubiKey PIV #12345678':
PKCS#11 login failed: error 7
login failed
pkcs11_get_key failed
sign_and_send_pubkey: signing failed for RSA "Public key for Retired Key 2": error in libcrypto
Received disconnect from 192.168.22.102 port 22:2: Too many authentication failures
Disconnected from 192.168.22.102 port 22
```

I feel like this may be the same as https://github.com/tpm2-software/tpm2-pkcs11/issues/629#issuecomment-845961430.

**Comment by qpernil** [comment] 2022-11-07 08:04
The good thing is that this https://github.com/tpm2-software/tpm2-pkcs11/issues/629#issuecomment-845961430 confirms my analysis that CKF_LOGIN_REQUIRED flag is what determines whether tools ask for PIN. The problem we currently have is that the flag is per _token_ and we assume there will be at least one key which requires PIN on the token (the PIV application of the YubiKey), which is always true for a PIV-compliant device, and typically true for a YubiKey as well. There are two things we could do - we could regard each PIV _key_ as it's own token and hence be able to set the flag per key, or we could set the flag based on all keys (as we kind of do now, but it's currently hard-coded) so that we would set it to false if all keys that are present had a pin-policy of 'never'. I think the latter makes more sense. Do you think it is an acceptable solution to require all keys have a pin-policy of never ? That would be a bit limiting. But You could at least enable touch, which is in a way is a more secure way to ensure keys are not used without user consent.

**Comment by qpernil** [comment] 2022-11-07 08:07
And just to make it 100% clear, CKF_LOGIN_REQUIRED is per token per the pkcs#11 specification, so that is not something we could change in yubico-piv-tool.

**Comment by mouse07410** [comment] 2022-11-07 11:56
> `CKF_LOGIN_REQUIRED` flag is what determines whether tools ask for PIN

Now I'm confused: in that case how does my PIV card work with a badge reader lock on the door? Why is the reader able to interact with the `CARD_AUTH` key without login PIN?

Could you add a few words clarifying why software tools cannot emulate the same behavior?

**Comment by qpernil** [comment] 2022-11-07 13:09
@mouse07410 Im guessing it uses a key that does not require PIN, and probably just 'knows' this because the PIV spec says so. Also, I'm guessing it isn't using libykcs11. If it was using the current libykcs11 that would not work because we keep track of the login state in software in libykcs11, in an attempt to fail at the proper times according to the pkcs11 spec (and knowing that we always set CKF_LOGIN_REQUIRED). If we instead started setting that flag based on actual PIN policies we need to change that. We could change it to only do software checks if we set the flag, or perhaps not at all, and just let the card indicate failure. That would mean we will fail later, so perhaps not fully fulfilling the pkcs#11 spec (and perhaps failing tests), but that may be better from a pragmatic point of view. Such a change does have a rather big chance of breaking things that do work now..

**Comment by qpernil** [comment] 2022-11-07 13:17
@mouse07410 just to point this out.. If the badge reader was using _any_ pkcs11 that module would have to either set or not set the CKF_LOGIN_REQUIRED flags _for the whole token_ (unless it presents every key as a single-key token). Unless all keys have the same PIN policy (which they can't according to PIV but can on a YubiKey) either would be wrong for some keys. And the decisions to always set that flag in libykcs11 was based on the fact that we find it better to get a few too many PIN requests than having an application fail because it didn't ask for PIN when it was actually needed. (And as I said, currently libykcs11 actually does some software checks so it would fail for that reason first as things stand now). So unless I'm missing something there is no way a pkcs#11 module can tell an application that only some keys require PIN. Contrast with the fact that it _can_ tell if PIN is required every time for each key. If you ask me this is a mistake in the pkcs#11 spec..
