### ISSUE TITLE
libykcs11.dll doesn't work on Windows OpenSSH

### ISSUE THREAD

**Issue by C0D3-M4513R** [Yubico/yubico-piv-tool#442] opened 2023-07-29 12:47 UTC
```
PS C:\Windows\System32\WindowsPowerShell\v1.0> ssh-agent -d
agent_start pid:12060, dbg:1
client pid 17564 connected
agent_process_connection pipe:0000000000000188
debug1: get_con_client_info: sshagent_con_username: restricted 
debug1: client type: restricted user
debug1: process agent request type 20
debug1: find_helper: using "C:\\Program Files\\OpenSSH\\ssh-pkcs11-helper.exe" as helper
process_add_smartcard_key: failed to add key to store. count:-1
debug1: iocp error: 109 on 0000028780BD6500
debug1: connection 0000028780BD6500 clean up
debug1: iocp error: 6 on 0000000000000000
```
```
PS C:\Users\xxx> ssh-add -s "C:\Program Files\Yubico\Yubico PIV Tool\bin\libykcs11.dll" -vvv
Enter passphrase for PKCS#11:
Could not add card "C:\Program Files\Yubico\Yubico PIV Tool\bin\libykcs11.dll": agent refused operation
```
```
PS C:\Users\xxx> ssh sn
dlopen C:\\Program Files\\Yubico\\Yubico PIV Tool\\bin\\libykcs11.dll failed: The specified module could not be found.
```
```
PS C:\Users\XXX> ssh -V
OpenSSH_for_Windows_9.2p1, LibreSSL 3.7.2
```

**Comment by a-dma** [comment] 2023-08-07 15:14
I don't know if OpenSSH for Windows behaves differently, but `ssh-agent` blocks PKCS#11 and FIDO providers that are not in some pre-determined paths. You can specify additional allowed paths at runtime by passing `-P` to `ssh-agent`. Could you try adding that?

If that's still not enough, then please turn on debugging in `ykcs11` by setting the environment variable `YKCS11_DBG=9` and paste the resulting output. Keep in mind that depending on the operations, user PINs will be logged.

**Comment by qpernil** [comment] 2023-08-21 15:33
This looks like you need to add the location of libykcs11.dll to the path. This is caused by the fact that openssh-agent loads the libykcs11.dll in a way that doesn't find dependencies (libykpiv.dll for example) in the directory where it loads the specified dll from. The fix for this has to be implemented in the ssh code. Please let me know if that works.

**Comment by qpernil** [comment] 2023-08-30 08:58
Well you will most likely have to add it to the system (not user) path, as the ssh-agent is running as a service. And after adding to the system path you also need to re-start the ssh-agent service for the path to take effect.

**Closed as completed** 2023-09-06 09:40 UTC
