### ISSUE TITLE
SCardBeginTransaction on card #16389519 failed after 0 retries, rc=ffffffff8010001d

### ISSUE THREAD

**Issue by skevy** [Yubico/yubico-piv-tool#330] opened 2021-10-28 21:58 UTC
Hi there!

I'm encountering an issue that I've spent some time digging into and I wonder if the authors of this library + Yubico would be able to provide any further details or remediations.

We use our Yubikey's in PIV mode and add them to ssh-agent using the dylib provided by this tool.

I've noticed recently (specifically, when I got a new M1 laptop, but still with macOS 11.6) that, even though the keys in the ssh-agent have not expired (we expire them at 14400 seconds), usage of the keys by ssh returns:

```
sign_and_send_pubkey: signing failed for RSA "Public key for PIV Authentication" from agent: agent refused operation
```

It seemed to happen at random times, and after this occurred, running `ssh-add -l` would still show the two keys in ssh-agent.

I decided today to spend some time debugging this, and ran `YKCS11_DBG=1 ssh-agent -d`. The logs are here https://gist.github.com/skevy/9a9f2662ac1143b5ba5352296aa3cb35 (first file is the log when the error happens, second log is the log when I can successfully use the key).

Looking at these logs, I noticed it logged:

`SCardBeginTransaction on card #16389519 failed after 0 retries, rc=ffffffff8010001d`

And digging into the actual return code, it's `SCARD_E_NO_SERVICE`. After some Googling, it became apparent that this can occur when PCSC stops running on the machine.

Sure enough, after I successfully add my Yubikey to my ssh-agent, I see `/System/Library/Frameworks/PCSC.framework/Versions/A/XPCServices/com.apple.ctkpcscd.xpc/Contents/MacOS/com.apple.ctkpcscd` running. After some undetermined amount of time, this process is forced to exit by the kernel with this log message:

`memorystatus: killing_idle_process pid 28470 [com.apple.ctkpcscd] jetsam_reason->osr_code: 9`.

In addition, by killing this process manually, I can now provide a consistent reproduction of the bug that started my investigation.

My question is: have you seen or heard of this before? Is this a bug in Apple's PSCS driver? Is there anyway for _this_ tool to somehow force this process to continue running on macOS? It seems to be started automatically when doing `ssh-add -s`...not sure how that's happening though.

Thanks in advance for the help!

**Comment by qpernil** [comment] 2021-11-02 19:39
We have a function called ShouldReconnect on master now, which decides if SCardReconnect should be called.
I'd be interested to know if this a an error code that should be included in the list in ShouldReconnect(). I can create a branch with it included if you'd be willing to test. Or you could simply modify and build yourself. Let me know.
/Per

**Comment by skevy** [comment] 2021-11-02 19:48
@qpernil I made the change you mentioned, and the new output is this:

```
debug1: pkcs11_check_obj_bool_attrib: provider 0x600000248280 slot 0 object 86: attrib 514 = 0
debug: /Users/adam_miskiewicz/repos/yubico-piv-tool/ykcs11/ykcs11.c:2834 (C_Sign): In
Reconnect card #16389519 attempt 1, previous rc=ffffffff8010001d
SCardReconnect on card #16389519 failed, rc=ffffffff8010001d
debug: /Users/adam_miskiewicz/repos/yubico-piv-tool/ykcs11/mechanisms.c:299 (sign_mechanism_final): ykpiv_sign_data with key 9a failed: Error in PCSC call
debug: /Users/adam_miskiewicz/repos/yubico-piv-tool/ykcs11/ykcs11.c:2894 (C_Sign): sign_mechanism_final failed
debug: /Users/adam_miskiewicz/repos/yubico-piv-tool/ykcs11/ykcs11.c:2907 (C_Sign): Out
C_Sign failed: 48
debug1: pkcs11_k11_free: parent 0x600000254000 ptr 0x0 idx 0
process_sign_request2: sshkey_sign: error in libcrypto
```

So it did _try_ to reconnect, but it's erroring when calling PCSC (which makes sense, because the pcsc daemon has quit).

How can we make this tool properly start the pcsc daemon?

**Comment by qpernil** [comment] 2021-11-03 08:17
Thanks a lot for your debugging effort, very helpful to understand the problem. As you know ykcs11 only interacts with platform-independent pcsc function calls. The ShouldReconnect was added to deal with slightly different error codes on macOS compared to Windows and Linux / pcsclite. I'd like to keep any changes to still only calling pcsc functions, but possibly reacting a bit differently depending on platform or error code. In this case we could try doing a full disconnect / connect, or even re-establishing the pcsc context. I'll see if I can reproduce the problem, and if not maybe you could try out some changes I'll push on a new branch, let's call it macos-no-service.

**Comment by qpernil** [comment] 2021-11-03 09:25
I'm on Monterey, and I can't seem to reproduce the problem. There is a process by the name you mention above, but killing it does not seem to disturb the PCSC API. Also, it takes some time for this process to (re)appear, but the PCSC API keeps working the whole time. I can create some code to test different reconnect strategies if you're willing to test.
I will also double-check this on a M1 mac mini I have access to a bit later.

**Comment by alexeyantropov** [comment] 2021-11-03 09:51
I can help with check on M1 with macOS Big Sur, if needed.

**Comment by geigeralex** [comment] 2021-11-03 09:56
Hello, if this helps, there is always one PCSC running, and PCSC respawns automatically if it is killed. In the Activity Monitor, I also see Idle Wake-Ups are running every second on this process(so it never dies).

But, when you start ssh-agent, it also starts the second PCSC process, which dies due to inactivity. Here are some examples:

```
ps aux | grep PCSC                                                                                                                                                                                                                                                                                                     
geiger           37086   0.1  0.1 408106080   4592   ??  Ss    1:02PM   1:03.36 /System/Library/Frameworks/PCSC.framework/Versions/A/XPCServices/com.apple.ctkpcscd.xpc/Contents/MacOS/com.apple.ctkpcscd
geiger           52137   0.0  0.0 408067536   3248   ??  Ss   10:23AM   0:00.07 /System/Library/Frameworks/PCSC.framework/Versions/A/XPCServices/com.apple.ctkpcscd.xpc/Contents/MacOS/com.apple.ctkpcscd
```

PID 37086 is always running
PID 52137 - started by ssh-agend and will die after some inactivity time(see launchd.log below)

```
2021-11-03 10:51:23.661065 (pid/52136/com.apple.ctkpcscd [52137]) <Notice>: service exited: dirty = 0, supported pressured-exit = 1
2021-11-03 10:51:23.661089 (pid/52136/com.apple.ctkpcscd [52137]) <Notice>: jettisoned: JETSAM_REASON_MEMORY_IDLE_EXIT
2021-11-03 10:51:23.661096 (pid/52136/com.apple.ctkpcscd [52137]) <Notice>: service state: exited
2021-11-03 10:51:23.661105 (pid/52136/com.apple.ctkpcscd [52137]) <Notice>: internal event: EXITED, code = 0
2021-11-03 10:51:23.661136 (pid/52136/com.apple.ctkpcscd [52137]) <Notice>: service state: not running
2021-11-03 10:51:23.661150 (pid/52137 [com.apple.ctkpc]) <Notice>: shutting down
2021-11-03 10:51:23.661177 (pid/52137/com.apple.MTLCompilerService) <Notice>: internal event: PETRIFIED, code = 0
2021-11-03 10:51:23.661202 (pid/52137/com.apple.audio.Core-Audio-Driver-Service.helper) <Notice>: internal event: PETRIFIED, code = 0
2021-11-03 10:51:23.661237 (pid/52137/com.apple.audio.Core-Audio-Driver-Service) <Notice>: internal event: PETRIFIED, code = 0
2021-11-03 10:51:23.661293 (pid/52137 [com.apple.ctkpc]) <Notice>: cleaning up
2021-11-03 10:51:23.661308 (system) <Notice>: removing child: pid/52137
```

**Comment by skevy** [comment] 2021-11-04 13:58
To echo @geigeralex...I was also seeing `JETSAM_REASON_MEMORY_IDLE_EXIT` in the logs. I actually don't usually have two pcscd's running...I'm not really sure why.

And yes @qpernil, I'm 100% happy to test anything you need. This is pretty annoying for us @ Airbnb, so we're eager to help get this fixed :)

**Comment by alexeyantropov** [comment] 2021-11-08 13:53
> To echo @geigeralex...I was also seeing `JETSAM_REASON_MEMORY_IDLE_EXIT` in the logs. I actually don't usually have two pcscd's running...I'm not really sure why.
> 
> And yes @qpernil, I'm 100% happy to test anything you need. This is pretty annoying for us @ Airbnb, so we're eager to help get this fixed :)

Do you have same problems on macOS Monterey? Or only on Big Sur?

**Comment by qpernil** [comment] 2021-11-08 14:02
I have not seen this problem, but I haven't run for any length of time either. It would be interesting to know from you guys if you run some PCSC client that we know doesn't have any special knowledge of how to start the macos pcsc deamon when the daemon has exited, if that gets it going again ? I.e. if it would possibly help for us to do a complete close / open cycle in the library. I guess a good test would be to use either piv-tool or yubihsm-auth to do something that interacts with a YubiKey. Both of those to straight up PCSC calls without any tricks to start deamons.

**Comment by qpernil** [comment] 2021-11-08 22:53
Here is some code that tests an alternative approach, please let me know if this makes any difference. Not that the code is just a draft to test if this approach has any merit. https://github.com/Yubico/yubico-piv-tool/pull/332

**Comment by geigeralex** [comment] 2021-11-09 07:32
It looks like uninstalling YubiKey Manager and rebooting a mac after that solved the issue for me.

**Comment by qpernil** [comment] 2021-11-09 08:12
Would yo care to share what exactly was changed by the uninstall ? No more stopping of the pcsc daemon ? Something else ? Glad to hear things working, but still would like to understand why..

**Comment by geigeralex** [comment] 2021-11-09 08:27
I think I was happy too early.  Exactly, there were no more stopping of the pcsc daemon yesterday and today for several hours, but now it started again, every X minutes pcsc stops.

**Comment by qpernil** [comment] 2021-11-09 08:33
OK, then maybe testing my changes in https://github.com/Yubico/yubico-piv-tool/pull/332 could be of interest. This code will check if the pcsc context has gone invalid, and re-establish it if so. It will also reconnect the card with a remembered reader name if that happens. The code is not properly checking that the same yubikey is inserted as of now, that will be added later if this works.

**Comment by geigeralex** [comment] 2021-11-09 08:48
> then maybe testing my changes in #332 could be of interest

I'm testing already, thank you.

**Comment by qpernil** [comment] 2021-11-09 08:50
Just note that I force-pushed a bugfix a few minutes ago for the code, for the case it lost the context. That would always fail with the code from yesterday

**Comment by qpernil** [comment] 2021-11-09 09:01
If the context isn't detected as invalid it may be worth trying to call SCardReleaseContext + SCardEstablishContext for the specific error code you received, SCARD_E_NO_SERVICE. I'm ready to push a change that does that when you let me know.

**Comment by geigeralex** [comment] 2021-11-09 10:20
Here is the debug output.

`debug1: new_socket: type = CONNECTION
debug3: fd 4 is O_NONBLOCK
debug1: process_message: socket 1 (fd=4) type 11
debug2: process_request_identities: entering
debug1: process_message: socket 1 (fd=4) type 13
debug1: process_sign_request2: entering
debug1: process_sign
debug1: check 0x600003ed4120 /usr/local/lib/libykcs11.2.2.1.dylib Public key for PIV Authentication
debug: /Users/geiger/Git/yubico-piv-tool/ykcs11/ykcs11.c:1809 (C_FindObjectsInit): In
debug: /Users/geiger/Git/yubico-piv-tool/ykcs11/ykcs11.c:1842 (C_FindObjectsInit): Initialized search with 3 parameters
debug: /Users/geiger/Git/yubico-piv-tool/ykcs11/objects.c:303 (get_doa): For data object 0, get
debug: /Users/geiger/Git/yubico-piv-tool/ykcs11/objects.c:307 (get_doa): CLASS
debug: /Users/geiger/Git/yubico-piv-tool/ykcs11/ykcs11.c:1860 (C_FindObjectsInit): Removing object 0
debug: /Users/geiger/Git/yubico-piv-tool/ykcs11/objects.c:303 (get_doa): For data object 24, get
debug: /Users/geiger/Git/yubico-piv-tool/ykcs11/objects.c:307 (get_doa): CLASS
debug: /Users/geiger/Git/yubico-piv-tool/ykcs11/ykcs11.c:1860 (C_FindObjectsInit): Removing object 24
debug: /Users/geiger/Git/yubico-piv-tool/ykcs11/objects.c:303 (get_doa): For data object 26, get
debug: /Users/geiger/Git/yubico-piv-tool/ykcs11/objects.c:307 (get_doa): CLASS
debug: /Users/geiger/Git/yubico-piv-tool/ykcs11/ykcs11.c:1860 (C_FindObjectsInit): Removing object 26
debug: /Users/geiger/Git/yubico-piv-tool/ykcs11/objects.c:303 (get_doa): For data object 31, get
debug: /Users/geiger/Git/yubico-piv-tool/ykcs11/objects.c:307 (get_doa): CLASS
debug: /Users/geiger/Git/yubico-piv-tool/ykcs11/ykcs11.c:1860 (C_FindObjectsInit): Removing object 31
debug: /Users/geiger/Git/yubico-piv-tool/ykcs11/objects.c:394 (_get_coa): For certificate object 37, get
debug: /Users/geiger/Git/yubico-piv-tool/ykcs11/objects.c:398 (_get_coa): CLASS
debug: /Users/geiger/Git/yubico-piv-tool/ykcs11/ykcs11.c:1860 (C_FindObjectsInit): Removing object 37
debug: /Users/geiger/Git/yubico-piv-tool/ykcs11/objects.c:394 (_get_coa): For certificate object 61, get
debug: /Users/geiger/Git/yubico-piv-tool/ykcs11/objects.c:398 (_get_coa): CLASS
debug: /Users/geiger/Git/yubico-piv-tool/ykcs11/ykcs11.c:1860 (C_FindObjectsInit): Removing object 61
debug: /Users/geiger/Git/yubico-piv-tool/ykcs11/objects.c:394 (_get_coa): For certificate object 62, get
debug: /Users/geiger/Git/yubico-piv-tool/ykcs11/objects.c:398 (_get_coa): CLASS
debug: /Users/geiger/Git/yubico-piv-tool/ykcs11/ykcs11.c:1860 (C_FindObjectsInit): Removing object 62
debug: /Users/geiger/Git/yubico-piv-tool/ykcs11/objects.c:521 (get_proa): For private key object 86, get
debug: /Users/geiger/Git/yubico-piv-tool/ykcs11/objects.c:525 (get_proa): CLASS
debug: /Users/geiger/Git/yubico-piv-tool/ykcs11/objects.c:521 (get_proa): For private key object 86, get
debug: /Users/geiger/Git/yubico-piv-tool/ykcs11/objects.c:561 (get_proa): ID
debug: /Users/geiger/Git/yubico-piv-tool/ykcs11/objects.c:521 (get_proa): For private key object 86, get
debug: /Users/geiger/Git/yubico-piv-tool/ykcs11/objects.c:617 (get_proa): SIGN
debug: /Users/geiger/Git/yubico-piv-tool/ykcs11/ykcs11.c:1867 (C_FindObjectsInit): Keeping object 86
debug: /Users/geiger/Git/yubico-piv-tool/ykcs11/objects.c:521 (get_proa): For private key object 110, get
debug: /Users/geiger/Git/yubico-piv-tool/ykcs11/objects.c:525 (get_proa): CLASS
debug: /Users/geiger/Git/yubico-piv-tool/ykcs11/objects.c:521 (get_proa): For private key object 110, get
debug: /Users/geiger/Git/yubico-piv-tool/ykcs11/objects.c:561 (get_proa): ID
debug: /Users/geiger/Git/yubico-piv-tool/ykcs11/ykcs11.c:1860 (C_FindObjectsInit): Removing object 110
debug: /Users/geiger/Git/yubico-piv-tool/ykcs11/objects.c:760 (get_puoa): For public key object 111, get
debug: /Users/geiger/Git/yubico-piv-tool/ykcs11/objects.c:764 (get_puoa): CLASS
debug: /Users/geiger/Git/yubico-piv-tool/ykcs11/ykcs11.c:1860 (C_FindObjectsInit): Removing object 111
debug: /Users/geiger/Git/yubico-piv-tool/ykcs11/objects.c:760 (get_puoa): For public key object 135, get
debug: /Users/geiger/Git/yubico-piv-tool/ykcs11/objects.c:764 (get_puoa): CLASS
debug: /Users/geiger/Git/yubico-piv-tool/ykcs11/ykcs11.c:1860 (C_FindObjectsInit): Removing object 135
debug: /Users/geiger/Git/yubico-piv-tool/ykcs11/ykcs11.c:1874 (C_FindObjectsInit): 1 object(s) left after attribute matching
debug: /Users/geiger/Git/yubico-piv-tool/ykcs11/ykcs11.c:1878 (C_FindObjectsInit): Out
debug: /Users/geiger/Git/yubico-piv-tool/ykcs11/ykcs11.c:1889 (C_FindObjects): In
debug: /Users/geiger/Git/yubico-piv-tool/ykcs11/ykcs11.c:1918 (C_FindObjects): Can return 1 object(s), 1 remaining
debug: /Users/geiger/Git/yubico-piv-tool/ykcs11/ykcs11.c:1927 (C_FindObjects): Returning 1 objects, 0 remaining
debug: /Users/geiger/Git/yubico-piv-tool/ykcs11/ykcs11.c:1931 (C_FindObjects): Out
debug: /Users/geiger/Git/yubico-piv-tool/ykcs11/ykcs11.c:1939 (C_FindObjectsFinal): In
debug: /Users/geiger/Git/yubico-piv-tool/ykcs11/ykcs11.c:1965 (C_FindObjectsFinal): Out
debug: /Users/geiger/Git/yubico-piv-tool/ykcs11/ykcs11.c:2752 (C_SignInit): In
debug: /Users/geiger/Git/yubico-piv-tool/ykcs11/ykcs11.c:2822 (C_SignInit): Out
debug: /Users/geiger/Git/yubico-piv-tool/ykcs11/ykcs11.c:1741 (C_GetAttributeValue): In
debug: /Users/geiger/Git/yubico-piv-tool/ykcs11/objects.c:521 (get_proa): For private key object 86, get
debug: /Users/geiger/Git/yubico-piv-tool/ykcs11/objects.c:712 (get_proa): ALWAYS AUTHENTICATE
debug: /Users/geiger/Git/yubico-piv-tool/ykcs11/ykcs11.c:1786 (C_GetAttributeValue): Out
debug1: pkcs11_check_obj_bool_attrib: provider 0x6000001d0000 slot 0 object 86: attrib 514 = 0
debug: /Users/geiger/Git/yubico-piv-tool/ykcs11/ykcs11.c:2834 (C_Sign): In
SCardBeginTransaction failed, rc=ffffffff8010001d
SCardReconnect on card #15955947 rc=ffffffff8010001d
debug: /Users/geiger/Git/yubico-piv-tool/ykcs11/mechanisms.c:299 (sign_mechanism_final): ykpiv_sign_data with key 9a failed: Error in PCSC call
debug: /Users/geiger/Git/yubico-piv-tool/ykcs11/ykcs11.c:2894 (C_Sign): sign_mechanism_final failed
debug: /Users/geiger/Git/yubico-piv-tool/ykcs11/ykcs11.c:2907 (C_Sign): Out
C_Sign failed: 48
debug1: pkcs11_k11_free: parent 0x6000001cc000 ptr 0x0 idx 0
process_sign_request2: sshkey_sign: error in libcrypto`

**Comment by geigeralex** [comment] 2021-11-09 12:04
It works now like a charm; thank you for fixing this!


```
SCardBeginTransaction on card #15955947 failed, rc=ffffffff8010001d
SCardReleaseContext on card #15955947 rc=0
SCardEstablishContext on card #15955947 rc=0
SCardConnect on reader Yubico YubiKey OTP+FIDO+CCID card #15955947 rc=0

```

**Comment by qpernil** [comment] 2021-11-09 15:05
I've added code that checks the serial number after a reconnect, to detect cases where a different YubiKey has been inserted.

**Comment by skevy** [comment] 2021-11-09 16:41
Hi there @qpernil, this seems to be working great! I'm having similar experiences as others in this thread and it seems like it successfully renegotiates the connection, even if I force kill the PCSCD daemon. And I can also confirm that it still works if I unplug the Yubikey and plug it back in again.

**Comment by skevy** [comment] 2021-11-09 16:41
Would you be able to merge this soon and cut a release?

**Comment by qpernil** [comment] 2021-11-10 08:34
The last version of this seems to work for me when testing on macOS, Linux and Windows.

**Comment by alexeyantropov** [comment] 2021-11-10 15:43
> The last version of this seems to work for me when testing on macOS, Linux and Windows. I've only tested on Monterey and Ubuntu though. Anyone have it tested on other versions of macOS or Linux ?

Hello! I can (Big Sur), but I need a arm64 build for macOS.

**Comment by qpernil** [comment] 2021-11-15 19:17
Sorry for the delay, we're struggling a bit to create binaries that have the right linkage without creating a complete release

**Comment by skevy** [comment] 2021-11-30 19:01
@qpernil any updates on this? Could we just make a beta release with this change? I've been using this for some time now and it's solved the issue for me.

**Comment by qpernil** [comment] 2021-12-01 08:11
Im sorry for the delay. From next week we will start working on merging the pull requests, and will be planning a new release after that.

**Comment by alexeyantropov** [comment] 2021-12-01 11:09
> Im sorry for the delay. From next week we will start working on merging the pull requests, and will be planning a new release after that.

Thx! Will wait for the release!

**Comment by skevy** [comment] 2022-01-15 05:08
Just checking in on the release @qpernil ... we'd love to roll this out to folks.

**Comment by cploonker** [comment] 2022-01-21 23:38
Any updates on the release @qpernil ... It is very challenging to enter the password 100 times a day.

**Comment by qpernil** [comment] 2022-05-02 08:10
Sorry for not updating this issue in a long time. Version 2.3.0 contains this fix, see https://developers.yubico.com/yubico-piv-tool/Release_Notes.html. Hope that helps. Closing this issue now, please let us know if there are remaining issues.

**Closed by qpernil** 2022-05-02 08:10 UTC

**Comment by alexeyantropov** [comment] 2022-05-02 08:34
Thanks a lot! I'll try it soon!

**Comment by alexeyantropov** [comment] 2022-05-04 11:45
@qpernil I tested it for [319](https://github.com/Yubico/yubico-piv-tool/issues/319), they're related issues in my opinion.

I can confirm, the issue was fixed, thank you!
