### ISSUE TITLE
macOS 13 - Issue - use of libykcs11.dylib

### ISSUE THREAD

**Issue by radsec** [Yubico/yubico-piv-tool#387] opened 2022-06-23 18:24 UTC
Issues using Yubikeys for PIV slot for authentication via ssh-agent.

Issue:
`Could not add card "/usr/local/lib/libykcs11.dylib": agent refused operation.`

This is correctly working via macOS 12.4 but is not working in macOS 13 beta 2.

This might be an issue with accessory filtering/blocking.

**Comment by qpernil** [comment] 2022-06-27 17:11
The best way to gain info about what is happening is to run the SSH agent in debug mode (-d).
See here for more info https://www.ssh.com/academy/ssh/agent

**Comment by qpernil** [comment] 2022-06-27 17:13
And when running the agent in that mode it also helps to enable libykcs11 debugging by setting the environment variable YKCS11_DBG to 1, 2 or 3 (for the log level, 2 and up will show APDUs sent to the YubiKey)

**Comment by radsec** [comment] 2022-07-19 19:27
So here is the output, looks like the helper cannot start? Not really much info here on this or where to look next.

Console 1:
```shell
❯ export YKCS11_DBG=2
❯ ssh-agent -d -a /Users/test/.ssh/ssh_auth_sock -P /usr/local/lib/libykcs11.dylib
SSH_AUTH_SOCK=/Users/test/.ssh/ssh_auth_sock; export SSH_AUTH_SOCK;
echo Agent pid 10897;
debug1: new_socket: type = SOCKET
debug2: fd 3 setting O_NONBLOCK
debug1: new_socket: type = CONNECTION
debug3: fd 4 is O_NONBLOCK
debug1: process_message: socket 1 (fd=4) type 26
debug2: process_add_smartcard_key: entering
debug1: process_add_smartcard_key: add /usr/local/lib/libykcs11.dylib
debug1: pkcs11_start_helper: starting /usr/libexec/ssh-pkcs11-helper -vvv
read from helper failed: 0
```

Console 2:
```shell
❯ export YKCS11_DBG=2
❯ SSH_AUTH_SOCK=/Users/test/.ssh/ssh_auth_sock ssh-add -s /usr/local/lib/libykcs11.dylib -t 14400
Enter passphrase for PKCS#11:
Could not add card "/usr/local/lib/libykcs11.dylib": agent refused operation
```

**Comment by Endareth** [comment] 2022-07-20 01:38
Seeing the same issue after upgrading to latest macOS 13 beta, essentially the same output as @radsec, on a 2021 MBP M1 Pro.

**Comment by qpernil** [comment] 2022-08-22 08:34
How was the ykcs11 library (and dependencies) installed ? This looks like a code signing issue.

**Comment by ctrezevant** [comment] 2022-08-23 03:59
I concur-- Recently began experiencing the same issue. However, this is also true when I use the built-in pkcs11 provider as well as libykcs11:

```
$ ssh-add -s /opt/homebrew/Cellar/yubico-piv-tool/2.3.0/lib/libykcs11.2.3.0.dylib
Enter passphrase for PKCS#11:
Could not add card "/opt/homebrew/Cellar/yubico-piv-tool/2.3.0/lib/libykcs11.2.3.0.dylib": agent refused operation
```

```
$ ssh-add -s /usr/lib/ssh-keychain.dylib
Enter passphrase for PKCS#11:
Could not add card "/usr/lib/ssh-keychain.dylib": agent refused operation
```

Neither appears to work at this time. 

Running 12.5.1 (21G83) on an M1 Pro. 

```
$ ssh -V
OpenSSH_8.6p1, LibreSSL 3.3.6
```

**Comment by ctrezevant** [comment] 2022-08-23 04:12
Per https://opensource.apple.com/source/OpenSSH/OpenSSH-240.40.1/openssh/ssh-agent.c.auto.html, it would appear that there is a path-based whitelist of PKCS11 providers that can be loaded:

```c
#ifdef ENABLE_PKCS11
static void
process_add_smartcard_key(SocketEntry *e)
{
	char *provider = NULL, *pin = NULL, canonical_provider[PATH_MAX];
	int r, i, count = 0, success = 0, confirm = 0;
	u_int seconds;
	time_t death = 0;
	u_char type;
	struct sshkey **keys = NULL, *k;
	Identity *id;

	if ((r = sshbuf_get_cstring(e->request, &provider, NULL)) != 0 ||
	    (r = sshbuf_get_cstring(e->request, &pin, NULL)) != 0) {
		error("%s: buffer error: %s", __func__, ssh_err(r));
		goto send;
	}

	while (sshbuf_len(e->request)) {
		if ((r = sshbuf_get_u8(e->request, &type)) != 0) {
			error("%s: buffer error: %s", __func__, ssh_err(r));
			goto send;
		}
		switch (type) {
		case SSH_AGENT_CONSTRAIN_LIFETIME:
			if ((r = sshbuf_get_u32(e->request, &seconds)) != 0) {
				error("%s: buffer error: %s",
				    __func__, ssh_err(r));
				goto send;
			}
			death = monotime() + seconds;
			break;
		case SSH_AGENT_CONSTRAIN_CONFIRM:
			confirm = 1;
			break;
		default:
			error("%s: Unknown constraint type %d", __func__, type);
			goto send;
		}
	}
	if (realpath(provider, canonical_provider) == NULL) {
		verbose("failed PKCS#11 add of \"%.100s\": realpath: %s",
		    provider, strerror(errno));
		goto send;
	}
	if (match_pattern_list(canonical_provider, pkcs11_whitelist, 0) != 1) {
		verbose("refusing PKCS#11 add of \"%.100s\": "
		    "provider not whitelisted", canonical_provider);
		goto send;
	}
	debug("%s: add %.100s", __func__, canonical_provider);
	if (lifetime && !death)
		death = monotime() + lifetime;

	count = pkcs11_add_provider(canonical_provider, pin, &keys);
	for (i = 0; i < count; i++) {
		k = keys[i];
		if (lookup_identity(k) == NULL) {
			id = xcalloc(1, sizeof(Identity));
			id->key = k;
			id->provider = xstrdup(canonical_provider);
			id->comment = xstrdup(canonical_provider); /* XXX */
			id->death = death;
			id->confirm = confirm;
			TAILQ_INSERT_TAIL(&idtab->idlist, id, next);
			idtab->nentries++;
			success = 1;
		} else {
			sshkey_free(k);
		}
		keys[i] = NULL;
	}
send:
	free(pin);
	free(provider);
	free(keys);
	send_status(e, success);
}
```

**Comment by ctrezevant** [comment] 2022-08-23 04:20
I've figured out a temporary workaround.

On a fresh macOS installation, `/usr/local/lib` does not exist. If you create it, and copy a version of the libykcs11.dylib there, you'll be able to use it to add your card to `ssh-agent`:

```
$ sudo mkdir /usr/local/lib/
Enter PIN for 'Certificate For PIV Authentication (auth.piv.charlton.id.nhq)':

$ sudo cp /opt/homebrew/Cellar/yubico-piv-tool/2.3.0/lib/libykcs11.2.3.0.dylib /usr/local/lib/

$ ssh-add -s /usr/local/lib/libykcs11.2.3.0.dylib
Enter passphrase for PKCS#11:
Card added: /usr/local/lib/libykcs11.2.3.0.dylib
```

Presumably, this is the result of some oversight by Apple in terms of their `ssh-agent` configuration/subtle breaking changes to macOS' directory structure.

**Comment by ctrezevant** [comment] 2022-08-23 04:38
Another note. I did have to install a more recent version of openssh (`OpenSSH_9.0p1, OpenSSL 1.1.1q  5 Jul 2022`) as the version shipping with macOS (`OpenSSH_8.6p1, LibreSSL 3.3.6`) does not support my ecdsa-sha2-nistp384 key.

**Comment by qpernil** [comment] 2022-08-23 08:58
For my info, how did you install the newer openssh ?

**Comment by qpernil** [comment] 2022-08-23 09:03
I have seen comments in the past that the -P option to ssh-agent (can be seen via ssh-agent -h on macos) doesn't work, and hence that you can't add paths that it will accept. But /usr/local/lib is on the default accepted list. You workaround seems to confirm that /usr/local/lib works, at least. Personally I usually build yubico-piv-tool myself from source, and in that case it ends up there by default.

**Comment by Endareth** [comment] 2022-08-23 13:10
Sorry @ctrezevant , I think you’re seeing a different issue to this one. The whitelist issue is basically this one: https://github.com/Yubico/yubico-piv-tool/issues/118 from a couple of major versions back, and possibly this also: https://developer.apple.com/forums/thread/670307. Manually copying a hard linked version of the dylib to /use/local/lib is still the best workaround for that. I’m guessing you’ve only just encountered that issue due to Homebrew installing arm stuff in /opt/homebrew now?

This issue is occurring specifically on the current macOS 13 betas, where the dylib is hard linked into what should be the whitelisted location (and which was definitely working correctly with same version of all homebrew packages prior to this beta).

**Comment by ctrezevant** [comment] 2022-08-23 14:39
@qpernil I installed openssh via `brew install openssh`. This includes the full suite of ssh and its related tools (scp, sftp, slogin, ssh, ssh-add, ssh-agent, ssh-keygen, ssh-keyscan).

I did not replace the version of ssh-agent that shipped with the system, however. In the past I've had issues getting the auth socket and permissions initialized correctly for openssh's ssh-agent when run as a service via launchd. The openssh agent also lacks keychain support. 

@Endareth On further review I would agree, I was ultimately not experiencing a code-signing issue. Apologies for unwittingly derailing this thread.

**Comment by radsec** [comment] 2022-08-23 19:41
Hmm, update on my side. I already had the `/usr/local/lib` folders correctly but wanted to test some stuff using `brew install openssh` just to see if it would work.

My results shows that using the `openssh 9.0p-OpenSSL 1.1.1q` versions work so this appears to possibly be an Apple openssh bug maybe in regards to how they built the `LibreSSL 3.3.6`

**Comment by radsec** [comment] 2022-08-23 19:44
An alternative solution to not shipping a custom ssh-agent appear to add these lines to a user's `.ssh/config` file. The user experience is definitely sub-par as we internally have created some wrappers to this but it is a short-term solution.

Addition to `.ssh/config`
```shell
# .ssh/config
Host *
    PKCS11Provider /usr/local/lib/libykcs11.dylib
```

**Comment by ctrezevant** [comment] 2022-08-23 20:28
@radsec That solution is what I currently have in place. It seems that the Brew's `ssh` and Apple's `ssh-agent` will play nicely together with my key given the appropriate `PKCS11Provider` directive + dylib. 

Prior to Apple shipping `OpenSSH_8.6p1, LibreSSL 3.3.6` in Monterrey the issue I had been experiencing was that I _could_ load the appropriate PKCS#11 provider, but my key type was unsupported. On Linux, `OpenSSH_8.9p1 Ubuntu-3, OpenSSL 3.0.2 15 Mar 2022` works without issue. 

For what it's worth, my `ssh-agent` (Apple's version) doesn't seem to be invoking `/usr/libexec/ssh-pkcs11-helper` at all for some reason. Instead, it invokes the one from Brew's openssh package (`/opt/homebrew/Cellar/openssh/9.0p1_1/libexec/ssh-pkcs11-helper`).

Here's debug output from starting `ssh-agent`, connecting to a host, clearing all identities, and re-adding my yubikey:

```
$ export YKCS11_DBG=2
$ ssh-agent -d
SSH_AUTH_SOCK=/var/folders/2p/rw1p439j6vd1k43n7878krmh0000gn/T//ssh-QmfwJwRI5DdK/agent.745; export SSH_AUTH_SOCK;
echo Agent pid 745;
debug1: new_socket: type = SOCKET
debug2: fd 3 setting O_NONBLOCK
debug1: new_socket: type = CONNECTION
debug3: fd 4 is O_NONBLOCK
debug1: process_message: socket 1 (fd=4) type 27
debug2: process_extension: entering
debug2: process_ext_session_bind: entering
debug1: process_ext_session_bind: recorded ED25519 SHA256:Z60OWmpyBlZ2cJiHpMPEHQjVGfYOXgqlUUSF6S7SosE (slot 0 of 16)
debug1: process_message: socket 1 (fd=4) type 11
debug2: process_request_identities: entering
debug2: process_request_identities: replying with 0 allowed of 0 available keys
debug1: new_socket: type = CONNECTION
debug3: fd 4 is O_NONBLOCK
debug1: process_message: socket 1 (fd=4) type 11
debug2: process_request_identities: entering
debug2: process_request_identities: replying with 0 allowed of 0 available keys
debug1: new_socket: type = CONNECTION
debug3: fd 4 is O_NONBLOCK
debug1: process_message: socket 1 (fd=4) type 11
debug2: process_request_identities: entering
debug2: process_request_identities: replying with 0 allowed of 0 available keys
debug1: new_socket: type = CONNECTION
debug3: fd 4 is O_NONBLOCK
debug1: process_message: socket 1 (fd=4) type 19
debug2: process_remove_all_identities: entering
debug1: process_message: socket 1 (fd=4) type 9
debug2: process_remove_all_identities: entering
debug1: new_socket: type = CONNECTION
debug3: fd 4 is O_NONBLOCK
debug1: process_message: socket 1 (fd=4) type 20
debug2: process_add_smartcard_key: entering
debug1: process_add_smartcard_key: add /usr/local/lib/libykcs11.2.3.0.dylib
debug1: pkcs11_start_helper: starting /opt/homebrew/Cellar/openssh/9.0p1_1/libexec/ssh-pkcs11-helper -vvv
debug1: process_add
debug: /tmp/yubico-piv-tool-20220304-21735-wn5xft/yubico-piv-tool-2.3.0/ykcs11/ykcs11.c:121 (C_Initialize): In
debug: /tmp/yubico-piv-tool-20220304-21735-wn5xft/yubico-piv-tool-2.3.0/ykcs11/ykcs11.c:205 (C_Initialize): Out
debug: /tmp/yubico-piv-tool-20220304-21735-wn5xft/yubico-piv-tool-2.3.0/ykcs11/ykcs11.c:264 (C_GetInfo): In
debug: /tmp/yubico-piv-tool-20220304-21735-wn5xft/yubico-piv-tool-2.3.0/ykcs11/ykcs11.c:288 (C_GetInfo): Out
debug1: provider /usr/local/lib/libykcs11.2.3.0.dylib: manufacturerID <Yubico (www.yubico.com)> cryptokiVersion 2.40 libraryDescription <PKCS#11 PIV Library (SP-800-73)> libraryVersion 2.30
debug: /tmp/yubico-piv-tool-20220304-21735-wn5xft/yubico-piv-tool-2.3.0/ykcs11/ykcs11.c:321 (C_GetSlotList): In
debug: /tmp/yubico-piv-tool-20220304-21735-wn5xft/yubico-piv-tool-2.3.0/ykcs11/ykcs11.c:388 (C_GetSlotList): Initializing slot 0 for 'Yubico YubiKey OTP+FIDO+CCID'
Connect reader 'Yubico YubiKey OTP+FIDO+CCID'.
```

Another ssh config note- In recent OpenSSH versions, specifying `IdentitiesOnly yes` with `IdentityFile` pointing to your *public key* will enforce that ssh offers the appropriate key from your yubikey ([more info](https://utcc.utoronto.ca/~cks/space/blog/sysadmin/SSHIdentitiesOffered)). 

I use this in conjunction with the `PKCS11Provider` directive:

```
Host *
  IgnoreUnknown UseKeychain
  UseKeychain yes
  AddKeysToAgent yes
#linux  PKCS11Provider /usr/lib/x86_64-linux-gnu/libykcs11.so
#osx builtin  PKCS11Provider /usr/lib/ssh-keychain.dylib
  PKCS11Provider /usr/local/lib/libykcs11.dylib
  IdentitiesOnly yes
  IdentityFile ~/.ssh/id_yk5
```

**Comment by qpernil** [comment] 2022-08-24 10:28
I did some testing myself, on Monterey (12.5.1).
- I found that when you install openssh from brew you will run ssh-agent and all the other ssh programs from that install by default, hence the example above would be using the brew ssh-agent, unless I'm missing something.
- When using the brew ssh tools with the built-in ssh-agent (i.e. not starting one myself, just using the one automatically started) I found that I can load libykcs11.dylib if it's in /usr/local/lib. It will only list RSA keys however.
- When first manually starting the brew ssh-agent (ssh-agent zsh) I can also load libykcs11.dylib, and then it will also list ecdsa keys (when running from the shell started by that agent, so that is uses that agent). I have not tested if the p11 library needs to be in any particular location in that case.
- Running built-in versions of all the ssh tools (including the agent) it works the same as using the brew tools with the built-in agent, i.e. only RSA keys listed and the p11 needs to be in /usr/local/lib
So it seems to be down to the agent (probably the lowest denominator of tools and agent) if you can use ec keys. And the built-in one has a -P list by default. I've seen indications it can't be changed (i.e. -P doesn't work properly) but I'm not sure if that's still true.
Putting PKCS11Provider in the config file loads the p11 into the ssh program, so it is similar to specifying a p11 in the command line as far as I can gather. Hence it is independent of which agent is running.

So the most straight-forward way to use ec keys via an agent would then seem to be:
- brew install openssh
- possibly restart your shell to get the paths set up
- ssh-agent zsh
- ssh user@foo.bar.com
The above ssh invocation would have to be done from the shell started by the agent.

Please let me know if these findings agree with yours.

**Comment by qpernil** [comment] 2022-08-24 10:43
An additional note - if you have replaced the built-in ssh-agent with gnupg acting as an ssh-agent it will block access to the PCSC reader so that the ssh-agent you start manually according to the above won't be able to see any slots. If you force the gnupg agent to release the reader it works. This is true even though they use different applications on the YubiKey. This is a feature of the gnupg agent..

**Comment by qpernil** [comment] 2022-08-24 11:41
Stating the obvious probably, but for completeness: 
ssh-agent zsh
will start a new shell (zsh, specified on the command line) with the correct SSH_AUTH_SOCK env variable already set up.
SSH_AUTH_SOCK is used by all ssh tools to determine the name of the ssh-agent socket to connect to.

**Comment by qpernil** [comment] 2022-08-24 11:46
A note on PKCS11Provider:
If you use this it seems to me it is the same as specifying the -I option to ssh. As such it would suffer from the same drawback that you have to specify PIN every time you use ssh. But on the other hand it would support ec keys even if the ssh-agent doesn't (since it's not used un that case).

**Comment by qpernil** [comment] 2022-08-24 11:55
Also, I realize that my notes are not an answer to the original issue with Macos 13. Rather, it is my attempt to understand the situation on macos 12.5.1, since that has kind of also been discussed. On the other hand the trick of using the ssh-agent from brew 'manually' might also work on macos 13. Let me know.

**Comment by ctrezevant** [comment] 2022-08-24 14:35
@qpernil 

> hence the example above would be using the brew ssh-agent, unless I'm missing something.

This is actually not the case for me-- I'm using brew's `ssh` binary, but Apple's `ssh-agent` is what's actually getting invoked. I can confirm this with a process listing:

```
$ ps aux | grep ssh-agent
charlton         26843   0.0  0.0 407991888   2592   ??  S    10:26AM   0:00.02 /usr/bin/ssh-agent -l
```

> It will only list RSA keys however.

This is consistent with the behavior I observe (and may explain why I have to manually input my PIN). My ecdsa-sha2-nistp384 is not listed by the agent but remains usable through it, though this may be related to my use of the PKCS11Provider directive. 

```
$ ssh-add -L
The agent has no identities.
```

> if you have replaced the built-in ssh-agent with gnupg acting as an ssh-agent it will block access to the PCSC reader so that the ssh-agent you start manually according to the above won't be able to see any slots.

This is (finally) fixed as of gpg2 2.3+ with the addition of the `pcsc-shared` directive. Shared access between `gpg-agent` and `ssh-agent` works completely for me with the following scdaemon configuration: 

```
$ cat ~/.gnupg/scdaemon.conf
reader-port Yubico YubiKey
#need gpg2 2.3+
pcsc-shared
```

**Comment by qpernil** [comment] 2022-08-25 15:01
@ctrezevant I was referring to the ssh-agent -d example. If openssh from brew was installed (and the shell restarted to get the paths set) it would invoke the brew ssh-agent, would it not ? Again, maybe Im stating the obvious, but you can have more than one ssh-agent running as long as they use different socket names, and you will use the one pointed out by  SSH_AUTH_SOCK variable in the env that's active when you run the other ssh tools. I think we may be speaking across each other regarding which use case we're discussing. 

Regarding PKCS11Provider I think that it is processed by ssh, ssh-add etc and not ssh-agent. So in that case you will have the pkcs11 loaded directly in those tools and not in the agent (actually in the pkcs11 helper invoked by the agent). So you will not list OR use ec keys through the agent at all if I understand things correctly. Hence they work even if you run the original macos agent, simply because it's not used for those keys. And it sounds like you confirm you had to enter PIN each time, which corroborates that theory.

Thanks a lot for your info about gnupg, I was not aware of that new feature.

**Comment by qpernil** [comment] 2022-09-27 08:28
@radsec How is your status regarding the original problem ?

**Comment by piersatdoshii** [comment] 2022-09-27 10:20
For me, it looks like the latest macOS beta has resolved things, can now use the dylib correctly.

**Comment by qpernil** [comment] 2022-10-28 13:04
I'm closing this issue now as it seems mostly resolved as far as I understand things. Please open a new issue if needed.

**Closed by qpernil** 2022-10-28 13:04 UTC

**Comment by zoechi** [comment] 2023-12-01 09:36
I run into this with NixOS 
and just post this here in case someone ends up here like I did.

I also had to add `-P .../libykcs11.so` to `ssh-agent` to make it work, but I also discovered, that it needs the resolved name instead of a symlink.
```sh
❯ realpath /nix/store/22nh1p52m31pgnv69v52lmx0c0mrqvq1-yubico-piv-tool-2.3.1/lib/libykcs11.so       
/nix/store/22nh1p52m31pgnv69v52lmx0c0mrqvq1-yubico-piv-tool-2.3.1/lib/libykcs11.so.2.3.1
```
so this version worked
```sh
ssh-agent -d -P /nix/store/22nh1p52m31pgnv69v52lmx0c0mrqvq1-yubico-piv-tool-2.3.1/lib/libykcs11.so.2.3.1
```
With `ssh-add -s ...` it didn't matter whether the link or the resolved path was used.

**Comment by marfillaster** [comment] 2025-03-11 20:36
Sorry for necroposting. Here's how I made it work in Sequioa
```
$ eval $(ssh-agent -P '/opt/homebrew/Cellar/yubico-piv-tool/2.7.1/lib*/*')
$  ssh-add -s /opt/homebrew/Cellar/yubico-piv-tool/2.7.1/lib/libykcs11.2.7.1.dylib -t 300
Enter passphrase for PKCS#11:
Card added: /opt/homebrew/Cellar/yubico-piv-tool/2.7.1/lib/libykcs11.2.7.1.dylib
```

**Comment by davdpwr** [comment] 2025-08-08 19:55
Sequioa 15.6 

> Sorry for necroposting. Here's how I made it work in Sequioa
> 
> ```
> $ eval $(ssh-agent -P '/opt/homebrew/Cellar/yubico-piv-tool/2.7.1/lib*/*')
> $  ssh-add -s /opt/homebrew/Cellar/yubico-piv-tool/2.7.1/lib/libykcs11.2.7.1.dylib -t 300
> Enter passphrase for PKCS#11:
> Card added: /opt/homebrew/Cellar/yubico-piv-tool/2.7.1/lib/libykcs11.2.7.1.dylib
> ```

I'm on Sequioa 15.6 (24G84) and that's not working for me hmmm

```
Enter passphrase for PKCS#11: 
Could not add card "/opt/homebrew/Cellar/yubico-piv-tool/2.7.1/lib/libykcs11.2.7.1.dylib": agent refused operation
```

**Comment by marfillaster** [comment] 2025-08-14 01:21
Here's my latest `~/.zshrc`.

```
export YUBIPIVTOOLPREFIX="$(greadlink -f $(brew --prefix yubico-piv-tool))"
alias ssh-add-card="ssh-add -s $YUBIPIVTOOLPREFIX/lib/libykcs11.dylib"
eval $(cat $HOME/.ssh/ssh-agent.env 2>/dev/null)
if [[ ! -S "$SSH_AUTH_SOCK"  ]] || [[ "$SSH_AUTH_SOCK" =~ "Listeners" ]] || [[ ! "$(ps -p $SSH_AGENT_PID -o command 2>/dev/null | tail -n 1)" =~ "ssh-agent" ]]; then
  eval $(ssh-agent -P "usr/lib*/*,/usr/local/lib*/*,$YUBIPIVTOOLPREFIX/lib*/*" | head -n 2 | tee $HOME/.ssh/ssh-agent.env)
  ssh-add-card
fi
```

Seems the ssh-agent no longer allows symlink.

**Comment by DerPlayer2001** [comment] 2025-10-30 14:29
With Tahoe 26.0.1 i still get the same Error...
```sh
❯ sshd -V
OpenSSH_10.2p1, OpenSSL 3.6.0 1 Oct 2025
❯ ssh-add -s /opt/homebrew/opt/yubico-piv-tool/lib/libykcs11.dylib -t 300
Enter passphrase for PKCS#11:
Could not add card "/opt/homebrew/opt/yubico-piv-tool/lib/libykcs11.dylib": agent refused operation
```
(note: `/opt/homebrew/opt/` always links to the latest Version)

**Comment by DerPlayer2001** [comment] 2025-10-31 16:33
I actually got some progress it turns out when I inspected the ssh agent with `ps -p $SSH_AGENT_PID -ww -o args=` it was run with the flag `-P /usr/lib*/*,/usr/local/lib*/*,/lib*/*` which does not include `/opt/homebrew/opt/yubico-piv-tool/lib/libykcs11.dylib`....
after killing my currently running agent with `kill $SSH_AGENT_PID` and starting it with `eval $(ssh-agent -P '/usr/lib*/*,/usr/local/lib*/*,/lib*/*,/opt/homebrew/Cellar/yubico-piv-tool/*')` I was able to add the card.

_edit: I see the simmilarities to @marfillaster 's script but it somehow didn't work for me_

**Comment by marfillaster** [comment] 2025-10-31 16:39
> I see the simmilarities to [@marfillaster](https://github.com/marfillaster) 's script but it somehow didn't work for me

Did you install `greadlink`? It's not installed by default.

**Comment by DerPlayer2001** [comment] 2025-10-31 17:27
> Did you install `greadlink`? It's not installed by default.

Aah I see I replaced it with the /opt/homebrew/opt link because I thought that would be clever but I now see why that didn’t work.

**Comment by robinp** [comment] 2026-06-16 20:34
A random reference point for posterity (success with nix-darwin):

```
nix-shell -p yubico-piv-tool 
eval $(ssh-agent -P "$(realpath $(dirname "$(which yubico-piv-tool)")/../lib)/*")
ssh-add -t 1h -s $(realpath $(dirname "$(which yubico-piv-tool)")/../lib/libykcs11.dylib)
Enter passphrase for PKCS#11: 
Card added: ...
```
The important point seems to be, the `-P` allowlist path can't be the full dylib itself, but needs to be a "dir/*" for whatever reason.

Can debug by starting `ssh-agent -d -P ...`, backgrounding it, exporting the SSH_AUTH_SOCK. Then will print what it chokes on.
