### ISSUE TITLE
How to provide PCSC library

### ISSUE THREAD

**Issue by jonahbron** [Yubico/yubico-piv-tool#256] opened 2020-06-28 00:54 UTC
I'm trying to install yubico-piv-tool on Clear Linux.  I've compiled and installed PCSClite from source:

https://pcsclite.apdu.fr/

But `./configure` can't find it.

```
$ ./configure
...
checking for winscard.h... no
checking between Mac/Windows winscard... no
configure: error: cannot find PCSC library
```

Checking the help output I saw the `with-pcsclib` and `with-pcscpath` flags.  I made my best guess on what to pass them, and at least the error changes slightly:

```
$ ./configure --with-pcscdir=../pcsc-lite-1.9.0/src/.libs/ --with-pcsclib=libpcsclite.so.1.0.0
...
checking for winscard.h... no
checking between Mac/Windows winscard... no
configure: checking for PCSC with custom lib
checking for PCSC/winscard.h... (cached) no
configure: error: cannot find custom PCSC library/headers
```

It seems like I'm providing the information incorrectly, but I don't know what to change to make it happy.  Any tips?

**Comment by a-dma** [comment] 2020-06-30 07:18
It looks like there's a parameter missing in the autconf file.

Try doing
`./configure --with-pcscdir=../pcsc-lite-1.9.0/src/.libs/ CFLAGS='-I ../pcsc-lite-1.9.0/src/'`

Generally speaking a better way of doing this is by building _and installing_ libpcsclite, if necessary with a custom prefix like `/tmp`, and then pointing `pkg-config` to the directory that contains `libpcsclite.pc` by setting the environment variable `PKG_CONFIG_PATH`.

**Comment by jonahbron** [comment] 2020-07-01 02:01
I did install it, but that didn't make a difference.  I can try experimenting with PKG_CONFIG_PATH, then revert to the CFLAGS flag if that doesn't work.

**Comment by aveenismail** [comment] 2020-12-03 14:25
Hi @jonahbron 
I know it's been long, but was the issue resolved? The last 2 releases of yubico-piv-tool no longer use automake and builds with cmake instead. Have that made any change for you?

**Comment by aveenismail** [comment] 2020-12-08 09:03
Closing this ticket for now, but feel free to reopen if the problem is still there

**Closed by aveenismail** 2020-12-08 09:03 UTC
