### ISSUE TITLE
read private key 

### ISSUE THREAD

**Issue by c3ph3us** [Yubico/yubico-piv-tool#76] opened 2016-06-16 22:01 UTC
how can i read private key / or store when generating on the device  ?  i see only -o option for public ?

**Comment by klali** [comment] 2016-06-17 07:01
I'm not sure what you're asking here. The private key is meant to never be extracted from the device once put in.

**Comment by c3ph3us** [comment] 2016-06-24 10:44
- use chip to generate on device key 
-  when it is generated on device (let import) - to have a backup  to put on second device 

i know that i can use pkcs11 engine & openssl to create ec key and puty it on device but why i can do this on device ?

**Comment by a-dma** [comment] 2016-06-27 07:45
As @klali said you can *never* extract private keys. This is by design and includes the possibility of making backup copies.
If you want a backup of your key, the only way is to generate it outside the device and import it.

**Comment by c3ph3us** [comment] 2016-07-09 01:07
@a-dma  -this is not a design issue -  it could be possible but yubico doesn't let us to have a master enc key for the device! - this is also another concern that we are not safe with our secrets (
as long as I can not change master key -  yubico can decrypt everything on the device).

**Comment by a-dma** [comment] 2016-07-11 07:44
I never said this is a design _issue_, not being able to extract private keys is a design _goal_.

What do you mean with a master encryption key? The YubiKey is implementing a standard (SP-800-73 in this case) which is what dictates which objects do and do not exist. Also, there is no data on the device for Yubico (or anybody) to decrypt. I'm confused.

**Comment by c3ph3us** [comment] 2016-08-18 18:00
@a-dma 

and how do you think the applets found themselves on the device??? 
did you ever heart about card manager key ?

**Comment by a-dma** [comment] 2016-08-19 09:14
Sorry, but I still don't understand where you're going with this. What kind of "card manager key" are you referring to? If you're talking about the PIV Management Key then that's an object within the PIV application running on the YubiKey and can be freely changed.
If you're talking about a card manager key for installing application onto the card then it's an entirely different thing and has nothing to do with PIV.

**Comment by mouse07410** [comment] 2016-08-23 17:18
The only way to "know" the private key is to generate if off-card, for example by OpenSSL or Java keytool, and then *load* the key pair to the card.

I recommend closing this issue.

**Comment by c3ph3us** [comment] 2016-08-23 20:49
@a-dma 

> If  you're talking about a card manager key for installing application onto...

yes this key allows to write and read from java card ( see npx chip :) ) 

@mouse07410 
> The only way to "know" the private key is to generate if off-card,

bulshit - this is the same as saying that String class objects (i'm referring to programming) are immutable ( if you can write into memory  then no!)  - heading to point -  if you don't know how to read from data storage it doesn't mean you cant!

disregards the matter that device is protected by the card encryption key (which is known to yubico)- if you have physical access to storage you always could rip off the device and read its data storage content - other matter is that this data is encrypted - and you either need to brute force encryption to know its real content (so encryption makes only some "small" difficulties in step to know your secret) 

golden rule "if you don't know nothing in theme the sit quiet"

see: 
- npx chip (card hardware)
- java virtual machine (card software) 
- card security (card manager -  to talk with it you need card management key )
http://www.smartcardbasics.com/

more readings:
http://csrc.nist.gov/publications/nistir/ir7539/nistir-7539-Symmetric_key_injection_final.pdf

**Comment by mouse07410** [comment] 2016-08-23 23:07
> golden rule "if you don't know nothing in theme the sit quiet"

It seems your manners go hand in hand with your wisdom. Otherwise you would've followed your own golden rule.

You asked:
> how can i read private key / or store when generating on the device ?

You then gave your own answer (then why did you ask your question, but don't bother to answer - I'm not interested):
> if you have physical access to storage you always could rip off the device and read its data storage content

So just do that, and stop polluting the forum where reasonable people discuss reasonable issues.

@a-dma I again suggest that this issue is closed.

**Comment by a-dma** [comment] 2016-08-24 07:54
This is not the place (nor the tone) to discuss this kind of topics.
The only reason why I left this issue open is that I was genuinely trying to see what kind of point you were trying to make, provided that we could have a polite discussion.
Since this is no longer the case, and given that the original question has been answered more than once, by more than one person, this issue has served its purpose.

Please refrain from replying or I will lock the conversation.

**Closed by a-dma** 2016-08-24 07:54 UTC
