### ISSUE TITLE
Build fails on Mac OS X with undeclared identifier 'slot__NULL'

### ISSUE THREAD

**Issue by bwesterb** [Yubico/yubico-piv-tool#60] opened 2016-01-06 14:28 UTC
On master (b08de955970c5cd544c740990fb68f496fedb814) and 1.2.2 the build fails on Mac OS X El Capitan with the following error.

```
util.c:265:10: error: use of undeclared identifier 'slot__NULL'
    case slot__NULL:
         ^
util.c:457:10: error: use of undeclared identifier 'hash__NULL'
    case hash__NULL:
         ^
util.c:476:14: error: use of undeclared identifier 'hash__NULL'
        case hash__NULL:
             ^
util.c:491:14: error: use of undeclared identifier 'hash__NULL'
        case hash__NULL:
             ^
util.c:510:10: error: use of undeclared identifier 'algorithm__NULL'
    case algorithm__NULL:
         ^
util.c:524:10: error: use of undeclared identifier 'pin_policy__NULL'
    case pin_policy__NULL:
         ^
util.c:536:10: error: use of undeclared identifier 'touch_policy__NULL'
    case touch_policy__NULL:
```

**Comment by klali** [comment] 2016-01-07 08:56
this is a duplicate of #28 gengetopt 2.22.6 is needed for compilation from git. If you use the released sources from https://developers.yubico.com/yubico-piv-tool/Releases/ they're already prepared for this.

**Closed by klali** 2016-01-07 08:56 UTC

**Comment by bwesterb** [comment] 2016-01-07 09:54
Thanks.
