### ISSUE TITLE
Possible bug in libykcs11.dylib

### ISSUE THREAD

**Issue by udf2457** [Yubico/yubico-piv-tool#205] opened 2019-08-07 14:44 UTC
As you are aware, the SSH developers have introduced support for ECC on PIV in OpenSSH 8 (https://www.openssh.com/releasenotes.html ("ssh(1), ssh-agent(1), ssh-add(1): Add support for ECDSA keys in PKCS#11 tokens").

_ssh-keygen -D /path/to/libykcs11.dylib -e -l_  correctly lists the ECC key.

However using ssh,  ssh prompts for the PIN but does not wait for the touch.
This only happens when using ECC keys.  When using RSA keys, SSH correctly waits for the touch before trying to finalise the signing and connection.
I therefore suspect there is a bug in libykcs11.dylib where SSH is not being told to wait for touch.

**Comment by a-dma** [comment] 2019-08-12 10:28
ssh doesn't know anything about touch, that is a YubiKey concept a and there is no way for the application to know about it.

I'm surprised you can even extract the fingerprint with `ssh-keygen`. As far as I remember that tries to parse the certificate and extract attributes from it, which ykcs11 doesn't support.

**Comment by qpernil** [comment] 2020-02-04 08:28
OpenSSH 8.x introduced EC support, and it works with ykcs11 from yubico-piv-tool 2.0.0.
Regarding touch, it is not handled by ykcs11 at all so my guess would be that you have different touch policies for your keys, it is set per key.

**Comment by udf2457** [comment] 2020-02-04 08:31
@qpernil have you tried EC with touch ?

**Comment by qpernil** [comment] 2020-02-04 08:49
Just tried it now, it works just like RSA.

**Comment by qpernil** [comment] 2020-02-04 08:50
I was using yubico-piv-tool 2.0.0, which was released a few days ago

**Comment by qpernil** [comment] 2020-02-07 11:34
I'm closing this as I cannot reproduce it. Please feel free to reopen it.

**Closed by qpernil** 2020-02-07 11:34 UTC
